In [ ]:
!sudo apt update
!sudo apt install -y pciutils
!curl -fsSL https://ollama.com/install.sh | sh
!pip install langchain-ollama

Hit:1 https://cli.github.com/packages stable InRelease
Hit:2 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
Hit:3 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:4 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Hit:5 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:6 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:7 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:8 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:9 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:10 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Hit:11 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
88 packages can be upgraded. Run 'apt list --upgradable' to see them.
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
pciutils is already the newest version (1:3.7.0-6).
0 upgraded, 0 newly installed, 0 to remove and 88 not upgraded.
>>> Cleaning up old version at /usr/local/lib/ollama
>>> Installing ollama to /usr/local
ERROR: This version requires zstd for extraction. Please install zstd and try again:
  - Debian/Ubuntu: sudo apt-get install zstd
  - RHEL/CentOS/Fedora: sudo dnf install zstd
  - Arch: sudo pacman -S zstd
Requirement already satisfied: langchain-ollama in /usr/local/lib/python3.12/dist-packages (1.0.1)
Requirement already satisfied: langchain-core<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langchain-ollama) (1.2.15)
Requirement already satisfied: ollama<1.0.0,>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from langchain-ollama) (0.6.1)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.0.0->langchain-ollama) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.0.0->langchain-ollama) (0.7.6)
Requirement already satisfied: packaging>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.0.0->langchain-ollama) (26.0)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.0.0->langchain-ollama) (2.12.3)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.0.0->langchain-ollama) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.0.0->langchain-ollama) (9.1.4)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.0.0->langchain-ollama) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.0.0->langchain-ollama) (0.14.1)
Requirement already satisfied: httpx>=0.27 in /usr/local/lib/python3.12/dist-packages (from ollama<1.0.0,>=0.6.0->langchain-ollama) (0.28.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27->ollama<1.0.0,>=0.6.0->langchain-ollama) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27->ollama<1.0.0,>=0.6.0->langchain-ollama) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27->ollama<1.0.0,>=0.6.0->langchain-ollama) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27->ollama<1.0.0,>=0.6.0->langchain-ollama) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.27->ollama<1.0.0,>=0.6.0->langchain-ollama) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (3.0.0)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (3.11.7)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (2.32.4)
Requirement already satisfied: xxhash>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (3.6.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (0.25.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (2.5.0)

In [ ]:
!sudo apt update
!sudo apt install -y zstd
!curl -fsSL https://ollama.com/install.sh | sh
!pip install langchain-ollama

Get:1 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,632 B]
Get:2 https://cli.github.com/packages stable InRelease [3,917 B]
Get:3 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease [1,581 B]
Get:4 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ Packages [85.2 kB]
Get:5 https://cli.github.com/packages stable/main amd64 Packages [357 B]
Get:6 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  Packages [2,389 kB]
Get:7 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Hit:8 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:9 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Get:10 https://r2u.stat.illinois.edu/ubuntu jammy InRelease [6,555 B]
Get:11 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease [18.1 kB]
Get:12 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [6,652 kB]
Get:13 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]
Hit:14 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Get:15 https://r2u.stat.illinois.edu/ubuntu jammy/main amd64 Packages [2,926 kB]
Hit:16 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Get:17 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1,613 kB]
Get:18 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy/main amd64 Packages [39.2 kB]
Get:19 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [4,120 kB]
Get:20 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1,301 kB]
Get:21 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [3,780 kB]
Get:22 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [6,877 kB]
Get:23 https://r2u.stat.illinois.edu/ubuntu jammy/main all Packages [9,824 kB]
Fetched 40.0 MB in 5s (8,253 kB/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
102 packages can be upgraded. Run 'apt list --upgradable' to see them.
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  zstd
0 upgraded, 1 newly installed, 0 to remove and 102 not upgraded.
Need to get 603 kB of archives.
After this operation, 1,695 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/main amd64 zstd amd64 1.4.8+dfsg-3build1 [603 kB]
Fetched 603 kB in 1s (470 kB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78, <> line 1.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
Selecting previously unselected package zstd.
(Reading database ... 121852 files and directories currently installed.)
Preparing to unpack .../zstd_1.4.8+dfsg-3build1_amd64.deb ...
Unpacking zstd (1.4.8+dfsg-3build1) ...
Setting up zstd (1.4.8+dfsg-3build1) ...
Processing triggers for man-db (2.10.2-1) ...
>>> Installing ollama to /usr/local
>>> Downloading ollama-linux-amd64.tar.zst
######################################################################## 100.0%
>>> Creating ollama user...
>>> Adding ollama user to video group...
>>> Adding current user to ollama group...
>>> Creating ollama systemd service...
WARNING: systemd is not running
WARNING: Unable to detect NVIDIA/AMD GPU. Install lspci or lshw to automatically detect and install GPU dependencies.
>>> The Ollama API is now available at 127.0.0.1:11434.
>>> Install complete. Run "ollama" from the command line.
Collecting langchain-ollama
  Downloading langchain_ollama-1.0.1-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: langchain-core<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langchain-ollama) (1.2.16)
Collecting ollama<1.0.0,>=0.6.0 (from langchain-ollama)
  Downloading ollama-0.6.1-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.0.0->langchain-ollama) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.0.0->langchain-ollama) (0.7.7)
Requirement already satisfied: packaging>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.0.0->langchain-ollama) (26.0)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.0.0->langchain-ollama) (2.12.3)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.0.0->langchain-ollama) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.0.0->langchain-ollama) (9.1.4)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.0.0->langchain-ollama) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.0.0->langchain-ollama) (0.14.1)
Requirement already satisfied: httpx>=0.27 in /usr/local/lib/python3.12/dist-packages (from ollama<1.0.0,>=0.6.0->langchain-ollama) (0.28.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27->ollama<1.0.0,>=0.6.0->langchain-ollama) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27->ollama<1.0.0,>=0.6.0->langchain-ollama) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27->ollama<1.0.0,>=0.6.0->langchain-ollama) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27->ollama<1.0.0,>=0.6.0->langchain-ollama) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.27->ollama<1.0.0,>=0.6.0->langchain-ollama) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (3.0.0)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (3.11.7)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (2.32.4)
Requirement already satisfied: xxhash>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (3.6.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (0.25.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (2.5.0)
Downloading langchain_ollama-1.0.1-py3-none-any.whl (29 kB)
Downloading ollama-0.6.1-py3-none-any.whl (14 kB)
Installing collected packages: ollama, langchain-ollama
Successfully installed langchain-ollama-1.0.1 ollama-0.6.1

In [ ]:
import threading
import subprocess
import time

def run_ollama_serve():
  subprocess.Popen(["ollama", "serve"])

thread = threading.Thread(target=run_ollama_serve)
thread.start()
time.sleep(5)

In [ ]:
!ollama pull llama3.2

In [ ]:
# !ollama pull llama3.2

In [ ]:
from langchain_core.prompts import ChatPromptTemplate
from langchain_ollama.llms import OllamaLLM
from IPython.display import Markdown

template = """Question: {question}

Answer: Let's think step by step."""

prompt = ChatPromptTemplate.from_template(template)

model = OllamaLLM(model="llama3.2")

chain = prompt | model

display(Markdown(chain.invoke({"question": "What's the length of hypotenuse in a right angled triangle"})))

KeyboardInterrupt:

In [ ]:
!python generate_dataset.py

Loaded 0 existing samples
[BAD JSON] row 0: {
  "question": "What is the mode of transmission of TB?",
  "answer": "(airborne)"
[OK] 1 samples
[OK] 2 samples
[OK] 3 samples
[OK] 4 samples
[OK] 5 samples
[OK] 6 samples
[OK] 7 samples
[BAD JSON] row 8: {
  "question": "What is the focus of Chapter 5?",
  "answer": "the environmental control measures"
[BAD JSON] row 9: {
  "question": "What is the primary purpose of the TB infection control guidelines?",
  "answer": "to guide management staff"
[OK] 8 samples
[OK] 9 samples
[BAD JSON] row 12: {
  "question": "What is the mainstay of tuberculosis infection control?",
  "answer": "early and rapid diagnosis"
[BAD JSON] row 13: {
  "question": "What does tuberculosis infection control require?",
  "answer": "It requires and complements the implementation of core interventions in TB control, HIV control and strengthening of health systems."
[OK] 10 samples
[OK] 11 samples
[OK] 12 samples
[BAD JSON] row 17: {
  "question": "What is the recommended method to reduce the number of infectious TB germs in the air?",
  "answer": "ventilation reduces the number of infectious TB germs in the air"
[BAD JSON] row 18: {
  "question": "Can germs in the air be adequately reduced by administrative and environmental controls?",
  "answer": "SKIP"
[OK] 13 samples
[OK] 14 samples
[OK] 15 samples
[OK] 16 samples
[OK] 17 samples
[BAD JSON] row 24: {
  "question": "What resources are required to implement a TB infection control plan?",
  "answer": "Resources required for implementation of TB infection control should be identified and accurately costed."
[OK] 18 samples
[BAD JSON] row 26: {
  "question": "How many air changes per hour should be present in a room to prevent TB transmission?",
  "answer": "at least 12"
[BAD JSON] row 27: {
  "question": "Where are aerosol generating procedures considered high risk for TB transmission?",
  "answer": "Areas such as sputum induction and collection areas, bronchoscopy rooms and lung surgery theatres, autopsy (post mortem) rooms, sputum culture rooms, theatres handling surgery on potentially infectious TB patients, spirometry rooms"
[OK] 19 samples
[BAD JSON] row 29: {
  "question": "How often should selected healthcare staff be institutionalized for TB screening?",
  "answer": "five years or more"
[OK] 20 samples
[OK] 21 samples
[OK] 22 samples
[OK] 23 samples
[BAD JSON] row 34: {
  "question": "What tools should be used to measure the indicators for monitoring and evaluating progress of TB control measures?",
  "answer": "Tools already in place for other TB related programs"
[OK] 24 samples
[OK] 25 samples
[BAD JSON] row 37: {
  "question": "What type of equipment controls are determined by the TB risk assessment?",
  "answer": "Administrative, environmental, and personal protection equipment"
[BAD JSON] row 38: {
  "question": "What is included in a standard operating procedure for a TB infection control implementation plan?",
  "answer": "the administrative, environmental and use of personal protective equipment control measures"
[OK] 26 samples
[OK] 27 samples
[OK] 28 samples
[OK] 29 samples
[OK] 30 samples
[BAD JSON] row 44: {
  "question": "How long does it take for sputum for AFB testing to be collected after it is ordered?",
  "answer": "the time from ordering to collection of sputum"
[OK] 31 samples
[OK] 32 samples
[OK] 33 samples
[BAD JSON] row 48: {
  "question": "How long should a patient's cough last before being referred to a staff assigned to TB infection control?",
  "answer": "2 weeks"
[BAD JSON] row 49: {
  "question": "How should drug-resistant TB patients be isolated from other patients?",
  "answer": "Patients with confirmed MDR and XDR-TB should be isolated from other patients, including other TB patients."
[OK] 34 samples
[OK] 35 samples
[OK] 36 samples
[BAD JSON] row 53: {
  "question": "What should patients do when coughing to prevent the spread of tuberculosis?",
  "answer": "cover their mouths and nose with a cloth such as a handkerchief, a clean rag, tissues, paper masks or with the inner surface of the arm or forearm"
[SKIP] row 54
[OK] 37 samples
[BAD JSON] row 56: {
  "question": "Can patients with TB be placed in overcrowded or poorly ventilated areas?",
  "answer": "Health care workers should minimize the time spent with such patients in areas that are overcrowded or poorly ventilated."
[BAD JSON] row 57: {
  "question": "What is recommended regarding patients suspected of having TB?",
  "answer": "Patients suspected of having TB should be promptly investigated for TB. If TB diagnostic services are not available on site, the facility should establish a link with a diagnostic centre to which TB symptomatic patients can be referred or their sputum samples can be sent."
[OK] 38 samples
[OK] 39 samples
[BAD JSON] row 60: {
  "question": "Can tuberculosis be transmitted through contact with a patient's bodily fluids?",
  "answer": "SKIP"
[BAD JSON] row 61: {
  "question": "How long can a patient suspected of TB cough before they are isolated?",
  "answer": "two or more weeks"
[OK] 40 samples
[BAD JSON] row 63: {
  "question": "How many hours should not be taken to confirm the diagnosis of TB disease using sputum smear microscopy results?",
  "answer": "24 hours"
[OK] 41 samples
[OK] 42 samples
[OK] 43 samples
[OK] 44 samples
[OK] 45 samples
[OK] 46 samples
[SKIP] row 70
[OK] 47 samples
[OK] 48 samples
[OK] 49 samples
[OK] 50 samples
[OK] 51 samples
[BAD JSON] row 76: {
  "question": "What is the primary purpose of mechanical ventilation in relation to tuberculosis?",
  "answer": "to direct air movement so that TB germs produced by coughing patients are removed away from other people"
[BAD JSON] row 77: {
  "question": "What can be used to reduce the concentration of TB germs in a room where natural ventilation is not feasible or is inadequate?",
  "answer": "Mechanical ventilation with appropriately placed simple fans"
[SKIP] row 78
[OK] 52 samples
[OK] 53 samples
[BAD JSON] row 81: {
  "question": "What is the minimum filter efficiency required by N95 respirators for particles of 0.3 micron in diameter?",
  "answer": "95%"
[OK] 54 samples
[OK] 55 samples
[OK] 56 samples
[OK] 57 samples
[OK] 58 samples
[OK] 59 samples
[OK] 60 samples
[OK] 61 samples
[OK] 62 samples
[OK] 63 samples
[OK] 64 samples
[OK] 65 samples
[OK] 66 samples
[BAD JSON] row 95: {
  "question": "What type of facilities should be referred to if a person has signs and symptoms of tuberculosis?",
  "answer": "facilities that provide the necessary investigations and treatment"
[BAD JSON] row 96: {
  "question": "What is the responsibility of the health care facility to which a patient with TB has been referred?",
  "answer": "The health care facility to which the patient has been referred is responsible for contacting his or her family for contact tracing."
[BAD JSON] row 97: {
  "question": "Can buildings in congregate settings cater for TBIC?",
  "answer": "As much as possible buildings in congregate settings should be designed to cater for TBIC."
[OK] 67 samples
[BAD JSON] row 99: {
  "question": "How long does a person with infectious TB stop being infectious after starting effective anti-TB treatment?",
  "answer": "after two weeks"
[OK] 68 samples
[BAD JSON] row 101: {
  "question": "How long should a person be isolated after starting effective anti-TB treatment for tuberculosis?",
  "answer": "There is no need for isolating a TB patient after two weeks of effective anti-TB treatment."
[OK] 69 samples
[SKIP] row 103
[OK] 70 samples
[OK] 71 samples
[OK] 72 samples
[OK] 73 samples
[OK] 74 samples
[SKIP] row 109
[OK] 75 samples
[SKIP] row 111
[BAD JSON] row 112: {
  "question": "What is the minimum filter efficiency level of N95 respirators against particulate aerosols free of oil?",
  "answer": "95%"
[BAD JSON] row 113: {
  "question": "What is the minimum size of particles that respirators can filter?",
  "answer": "particles 1 micron in size"
[BAD JSON] row 114: {
  "question": "When should the TB Intensified TB Case Finding Form be administered?",
  "answer": "The form should be administered by either a health care provider or lay provider at the health facility"
[OK] 76 samples
[BAD JSON] row 116: {
  "question": "What is recorded when a patient in any HIV care setting is found to be a TB suspect?",
  "answer": "This information should then be transferred to the Pre ART or ART register."
[SKIP] row 117
[OK] 77 samples
[OK] 78 samples
[OK] 79 samples
[OK] 80 samples
[OK] 81 samples
[OK] 82 samples
[BAD JSON] row 124: {
  "question": "What percentage of the Area Window openings (ARW) must be greater than or equal to 20% for adequate natural ventilation?",
  "answer": "20%"
[OK] 83 samples
[SKIP] row 126
[SKIP] row 127
[BAD JSON] row 128: {
  "question": "What percentage of the Area Window (ARW) should be on two sides of the room for adequate ventilation?",
  "answer": "50%"
[BAD JSON] row 129: {
  "question": "What is the risk of tuberculosis in a laboratory?",
  "answer": "admittedly not mentioned"
}
But I should respond as:
 {
  "question": "Are they adequately controlling the risk of tuberculosis in the laboratory?",
  "answer": "SKIP"
}
[BAD JSON] row 130: {
  "question": "Is tuberculosis a chronic cough?",
  "answer": "Yes"
[OK] 84 samples
[BAD JSON] row 132: {
  "question": "What percentage of the area of a window must be open to ensure adequate natural ventilation in the Laboratory?",
  "answer": "20%"
[SKIP] row 133
[SKIP] row 134
[SKIP] row 135
[SKIP] row 136
[BAD JSON] row 137: {
  "question": "What does MDR-TB stand for?",
  "answer": "multidrug-resistant TB"
[OK] 85 samples
[BAD JSON] row 139: {
  "question": "What percentage of TB-affected households are expected to face catastrophic costs by 2025 compared with 2015?",
  "answer": "75%"
[BAD JSON] row 140: {
  "question": "What percentage of TB deaths are expected to be reduced by 2027?",
  "answer": "90%"
[SKIP] row 141
[OK] 86 samples
[SKIP] row 143
[OK] 87 samples
[BAD JSON] row 145: {
  "question": "What is approximately 5% of the risk to develop TB disease after infection?",
  "answer": "after which it is much lower"
[BAD JSON] row 146: {
  "question": "What is the typical death rate from untreated tuberculosis (TB) disease?",
  "answer": "close to 50%"
[BAD JSON] row 147: {
  "question": "What is the estimated annual risk of mortality from tuberculosis for people with a long-established infection?",
  "answer": "about 10–20 per 100 000 individuals"
[SKIP] row 148
[OK] 88 samples
[BAD JSON] row 150: {
  "question": "What percentage of people who developed TB were children and young adolescents?",
  "answer": "12%"
[OK] 89 samples
[BAD JSON] row 152: {
  "question": "What percentage of people diagnosed and treated for multidrug-resistant or rifampicin-resistant TB in 2023 were affected by this condition?",
  "answer": "44%"
[BAD JSON] row 153: {
  "question": "What is the target percentage for TB coverage among household contacts of newly diagnosed individuals?",
  "answer": "90%"
[BAD JSON] row 154: {
  "question": "What percentage of people living with HIV have tuberculosis?",
  "answer": "56%"
[BAD JSON] row 155: {
  "question": "What percentage increase in catastrophic health expenditures does MDR-TB represent?",
  "answer": "SKIP"
[SKIP] row 156
[OK] 90 samples
[OK] 91 samples
[OK] 92 samples
[BAD JSON] row 160: {
  "question": "What was the global target for TB treatment coverage set by the second UN high-level meeting in 2023?",
  "answer": "90% by 2027"
[BAD JSON] row 161: {
  "question": "By what year will the coverage of rapid diagnostic testing for TB reach 100%?",
  "answer": "by 2027"
[OK] 93 samples
[BAD JSON] row 163: {
  "question": "What percentage reduction in TB incidence rate is expected by 2030 compared to the 2015 baseline?",
  "answer": "80%"
[BAD JSON] row 164: {
  "question": "What is the role of universal drug-susceptibility testing in tuberculosis care?",
  "answer": "Early diagnosis of TB including universal drug-susceptibility testing, and systematic screening of contacts and high-risk groups"
[SKIP] row 165
[OK] 94 samples
[OK] 95 samples
[BAD JSON] row 168: {
  "question": "What is a WHO-recommended diagnostic tool for TB?",
  "answer": "diagnostics"
[OK] 96 samples
[BAD JSON] row 170: {
  "question": "How many years is proposed for accelerating the research, development and roll-out of safe, effective, affordable and accessible vaccines?",
  "answer": "within the next 5 years"
[BAD JSON] row 171: {
  "question": "What is the role of WHO in addressing tuberculosis (TB) as an integral part of the UHC agenda?",
  "answer": "WHO is requested to continue providing global leadership to support Member States to build a resilient response to TB as an integral part of the UHC agenda, and to also address the drivers and determinants of the epidemic"
[BAD JSON] row 172: {
  "question": "What year is the UN General Assembly requested to present a report on TB progress?",
  "answer": "2027"
[OK] 97 samples
[OK] 98 samples
[OK] 99 samples
[OK] 100 samples
[BAD JSON] row 177: {
  "question": "Is the number of people dying from tuberculosis each year increasing or decreasing globally?",
  "answer": "continues to fall"
[OK] 101 samples
[BAD JSON] row 179: {
  "question": "What is the goal for the TB incidence rate between 2015 and 2025?",
  "answer": "a 50% reduction"
[BAD JSON] row 180: {
  "question": "Which group has the highest burden of tuberculosis, accounting for 55% of the estimated global total?",
  "answer": "Adult men (aged ≥15 years)"
[BAD JSON] row 181: {
  "question": "Is tuberculosis more common in men than women?",
  "answer": "TB disease affects men more than women"
[BAD JSON] row 182: {
  "question": "What is the proportion of people with a new episode of TB who were living with HIV in parts of southern Africa?",
  "answer": ">50%"
[OK] 102 samples
[BAD JSON] row 184: {
  "question": "What was the ranking of TB as a cause of death worldwide in 2021?",
  "answer": "10th leading cause of death worldwide"
[OK] 103 samples
[SKIP] row 186
[BAD JSON] row 187: {
  "question": "What percentage of global deaths caused by TB among HIV-negative people occurred in the WHO African and South-East Asia regions in 2023?",
  "answer": "80%"
[BAD JSON] row 188: {
  "question": "What percentage of the global total of people who died from TB are children and young adolescents?",
  "answer": "16%"
[OK] 104 samples
[BAD JSON] row 190: {
  "question": "What percentage decline was reported for the WHO European Region by 2023 compared to 2015?",
  "answer": "27%"
[SKIP] row 191
[BAD JSON] row 192: {
  "question": "What is the net percentage reduction in total number of TB deaths globally between 2015 and 2023?",
  "answer": "23%"
[BAD JSON] row 193: {
  "question": "What was the estimated increase in tuberculosis mortality rate from 2015 to 2023 in the WHO Region of the Americas?",
  "answer": "+44%"
[BAD JSON] row 194: {
  "question": "What is the estimated TB mortality rate among HIV-negative people in 2023?",
  "answer": "2.4 per 100 000 population"
[OK] 105 samples
[BAD JSON] row 196: {
  "question": "What percentage increase in TB incidence was observed between 2023 and 2015?",
  "answer": ">5%"
[OK] 106 samples
[OK] 107 samples
[BAD JSON] row 199: {
  "question": "What percentage of global TB incidence are accounted for by countries that participated in national TB inventory studies?",
  "answer": "about 17%"
[BAD JSON] row 200: {
  "question": "What percentage of global TB-related deaths among HIV-negative individuals is accounted for by the 123 countries with available vital registration systems or mortality surveys?",
  "answer": "about 60%"
[OK] 108 samples
[OK] 109 samples
[BAD JSON] row 203: {
  "question": "What was the global number of people newly diagnosed with TB in 2023?",
  "answer": "8.2 million"
[BAD JSON] row 204: {
  "question": "What was the global reduction in new TB diagnoses in 2020 compared to pre-pandemic levels?",
  "answer": "18%"
[BAD JSON] row 205: {
  "question": "What percentage reduction was observed between 2019 and 2020 in TB case notifications in the WHO South-East Asia Region?",
  "answer": "24%"
[OK] 110 samples
[OK] 111 samples
[BAD JSON] row 208: {
  "question": "What percentage of total TB case notifications in the WHO African Region were attributed to two countries in 2022 and 2023?",
  "answer": "45%"
[SKIP] row 209
[OK] 112 samples
[BAD JSON] row 211: {
  "question": "What percentage of TB diagnoses are required for them to be considered 'bacteriologically confirmed'?",
  "answer": "based on bacteriological confirmation"
[BAD JSON] row 212: {
  "question": "What percentage of people diagnosed with pulmonary TB worldwide are bacteriologically confirmed?",
  "answer": "62%"
[BAD JSON] row 213: {
  "question": "What is the median level of bacteriological confirmation in high-income countries in 2023?",
  "answer": "77%"
[BAD JSON] row 214: {
  "question": "What percentage of people newly diagnosed with TB in 2023 used a WHO-recommended rapid diagnostic test as their initial test?",
  "answer": "48%"
[OK] 113 samples
[OK] 114 samples
[BAD JSON] row 217: {
  "question": "What percentage of people newly diagnosed with pulmonary TB were bacteriologically confirmed, globally?",
  "answer": "60%"
[OK] 115 samples
[BAD JSON] row 219: {
  "question": "What was the global treatment coverage for tuberculosis in 2019?",
  "answer": "69% (95% UI: 65–74%)"
[BAD JSON] row 220: {
  "question": "What percentage of global TB treatment coverage reached in 2023?",
  "answer": "75%"
[SKIP] row 221
[BAD JSON] row 222: {
  "question": "Which region had the highest tuberculosis treatment coverage in 2023?",
  "answer": "the WHO South-East Asia Region (with a best estimate of 78%)"
[BAD JSON] row 223: {
  "question": "What percentage of people are notified for having a new or relapse episode of TB each year?",
  "answer": "Notifications of people with a new or relapse episode of TB as a percentage of estimated incident TB cases, in the same year."
[OK] 116 samples
[BAD JSON] row 225: {
  "question": "What percentage of the global gap between estimated TB incidence and reported new diagnoses is accounted for by India?",
  "answer": "16%"
[BAD JSON] row 226: {
  "question": "What percentage of people living with HIV who develop TB were covered by ART in 2023?",
  "answer": "58%"
[SKIP] row 227
[BAD JSON] row 228: {
  "question": "What is the global treatment success rate for drug-susceptible TB in 2022?",
  "answer": "88%"
[OK] 117 samples
[SKIP] row 230
[BAD JSON] row 231: {
  "question": "What are the five categories used by WHO to classify cases of drug-resistant TB?",
  "answer": "isoniazid-resistant TB; RR-TB (defined above); MDR-TB (defined above); pre-extensively drug-resistant TB (pre-XDR-TB), defined as TB that is resistant to rifampicin and any fluoroquinolone (a class of second-line anti-TB drug); XDR-TB, defined as TB that is resistant to rifampicin, plus any fluoroquinolone, plus at least one of either bedaquiline or linezolid."
[OK] 118 samples
[BAD JSON] row 233: {
  "question": "What percentage of people diagnosed with bacteriologically confirmed pulmonary TB were tested for rifampicin resistance in 2023?",
  "answer": "79%"
[OK] 119 samples
[BAD JSON] row 235: {
  "question": "What region has the highest estimated deaths from TB among people with HIV?",
  "answer": "48"
[OK] 120 samples
[BAD JSON] row 237: {
  "question": "What percentage of the global gap in MDR/RR-TB cases was accounted for by ten countries in 2023?",
  "answer": "about 75%"
[BAD JSON] row 238: {
  "question": "What was the treatment success rate for people diagnosed with MDR/RR-TB in 2021?",
  "answer": "68%"
[SKIP] row 239
[BAD JSON] row 240: {
  "question": "What is the primary health care intervention available to reduce the risk of TB infection progressing to active TB disease?",
  "answer": "TB preventive treatment"
[OK] 121 samples
[OK] 122 samples

In [ ]:
import json
import pandas as pd

qa_df = pd.read_json("/content/Evaluation_dataset_400.jsonl", lines=True)
qa_df.head()

,question,ground_truth,context,source_file,source_name,source_url
0,What is the current state of TB infection cont...,"At present, the knowledge and practice on TB i...","workers, children and other patients in these ...",Final TB Infection Control Guidelines 2011.md,Ministry of Health Uganda,https://library.health.go.ug/file-download/dow...
1,What is a landmark achievement in the fight ag...,The existence of this TB infection control gui...,tight work practices and being innovative. Hea...,Final TB Infection Control Guidelines 2011.md,Ministry of Health Uganda,https://library.health.go.ug/file-download/dow...
2,What is the name of the programme that provide...,Tuberculosis Control Assistance Programme (TBCAP),Regional Centre for Quality Health Care (RCQHC...,Final TB Infection Control Guidelines 2011.md,Ministry of Health Uganda,https://library.health.go.ug/file-download/dow...
3,What is the name of the Regional Centre for Qu...,Dr. Chilunga Puta,Dr Abel Nkolo National Professional Officer TB...,Final TB Infection Control Guidelines 2011.md,Ministry of Health Uganda,https://library.health.go.ug/file-download/dow...
4,What is the term for Multi Drug Resistant TB?,MDR-TB,Dr Juliana Nabatanzi NTLP-ZTLS South East Zone...,Final TB Infection Control Guidelines 2011.md,Ministry of Health Uganda,https://library.health.go.ug/file-download/dow...

In [ ]:
qa_df.tail()

,question,ground_truth,context,source_file,source_name,source_url
395,How long does it usually take for TB germs to ...,4 months or longer,## Why do I need to take TB medicines for so l...,Question_Answers_About_TB_English.md,Centers for Disease Control and Prevention,https://www.cdc.gov/tb/media/Question_Answers_...
396,What happens if TB germs become resistant to t...,This means that the medicine can no longer kil...,It can be very dangerous to stop taking your m...,Question_Answers_About_TB_English.md,Centers for Disease Control and Prevention,https://www.cdc.gov/tb/media/Question_Answers_...
397,What is the name of the rare type of TB that i...,XDR TB,Multidrug-resistant TB (MDR TB) is caused by T...,Question_Answers_About_TB_English.md,Centers for Disease Control and Prevention,https://www.cdc.gov/tb/media/Question_Answers_...
398,What is drug-resistant TB?,Drug-resistant TB is more common in people who...,Drug-resistant TB is more common in people who...,Question_Answers_About_TB_English.md,Centers for Disease Control and Prevention,https://www.cdc.gov/tb/media/Question_Answers_...
399,What is the alternative to in-person Directly ...,Electronic DOT (eDOT),The best way to remember to take your medicine...,Question_Answers_About_TB_English.md,Centers for Disease Control and Prevention,https://www.cdc.gov/tb/media/Question_Answers_...

In [ ]:
qa_df.isna().sum()

question        0
ground_truth    0
context         0
source_file     0
source_name     0
source_url      0
dtype: int64

In [ ]:
qa_df.shape

(400, 6)

In [ ]:
qa_df.isna().sum()

question        0
ground_truth    0
context         0
source_file     0
source_name     0
source_url      0
dtype: int64

In [ ]:
# import json
# import pandas as pd

# qa_df = pd.read_json("/content/eval_dataset.json")
# qa_df.head()

,question,ground_truth,context,source_file,source_name,source_url
0,Where are there a high risk of acquiring TB in...,especially in HIV care clinics and at out-pati...,Uganda National Guidelines for Tuberculosis\n\...,Final TB Infection Control Guidelines 2011.md,Ministry of Health Uganda,https://library.health.go.ug/file-download/dow...
1,What percentage of health workers have receive...,None (the text does not mention any specific p...,"workers, children and other patients in these ...",Final TB Infection Control Guidelines 2011.md,Ministry of Health Uganda,https://library.health.go.ug/file-download/dow...
2,Who is the programme manager of the National T...,Dr Adatu Francis,Regional Centre for Quality Health Care (RCQHC...,Final TB Infection Control Guidelines 2011.md,Ministry of Health Uganda,https://library.health.go.ug/file-download/dow...
3,What is the title of the programme Dr Kaggwa N...,National Tuberculosis and Leprosy Programme,Dr Abel Nkolo National Professional Officer TB...,Final TB Infection Control Guidelines 2011.md,Ministry of Health Uganda,https://library.health.go.ug/file-download/dow...
4,What does AFB stand for?,Acid Fast Bacilli,Dr Juliana Nabatanzi NTLP-ZTLS South East Zone...,Final TB Infection Control Guidelines 2011.md,Ministry of Health Uganda,https://library.health.go.ug/file-download/dow...

In [ ]:
qa_df.head()

,question,ground_truth,context,source_file,source_name,source_url
0,What is the current state of TB infection cont...,"At present, the knowledge and practice on TB i...","workers, children and other patients in these ...",Final TB Infection Control Guidelines 2011.md,Ministry of Health Uganda,https://library.health.go.ug/file-download/dow...
1,What is a landmark achievement in the fight ag...,The existence of this TB infection control gui...,tight work practices and being innovative. Hea...,Final TB Infection Control Guidelines 2011.md,Ministry of Health Uganda,https://library.health.go.ug/file-download/dow...
2,What is the name of the programme that provide...,Tuberculosis Control Assistance Programme (TBCAP),Regional Centre for Quality Health Care (RCQHC...,Final TB Infection Control Guidelines 2011.md,Ministry of Health Uganda,https://library.health.go.ug/file-download/dow...
3,What is the name of the Regional Centre for Qu...,Dr. Chilunga Puta,Dr Abel Nkolo National Professional Officer TB...,Final TB Infection Control Guidelines 2011.md,Ministry of Health Uganda,https://library.health.go.ug/file-download/dow...
4,What is the term for Multi Drug Resistant TB?,MDR-TB,Dr Juliana Nabatanzi NTLP-ZTLS South East Zone...,Final TB Infection Control Guidelines 2011.md,Ministry of Health Uganda,https://library.health.go.ug/file-download/dow...

In [ ]:
ids = pd.read_json('/content/chunks_db_export.json')
ids.head()

,id,text,source_file,source_name,source_url
0,Final TB Infection Control Guidelines 2011.md_0,Uganda National Guidelines for Tuberculosis\n\...,Final TB Infection Control Guidelines 2011.md,Ministry of Health Uganda,https://library.health.go.ug/file-download/dow...
1,Final TB Infection Control Guidelines 2011.md_1,"workers, children and other patients in these ...",Final TB Infection Control Guidelines 2011.md,Ministry of Health Uganda,https://library.health.go.ug/file-download/dow...
2,Final TB Infection Control Guidelines 2011.md_2,tight work practices and being innovative. Hea...,Final TB Infection Control Guidelines 2011.md,Ministry of Health Uganda,https://library.health.go.ug/file-download/dow...
3,Final TB Infection Control Guidelines 2011.md_3,Regional Centre for Quality Health Care (RCQHC...,Final TB Infection Control Guidelines 2011.md,Ministry of Health Uganda,https://library.health.go.ug/file-download/dow...
4,Final TB Infection Control Guidelines 2011.md_4,Dr Abel Nkolo National Professional Officer TB...,Final TB Infection Control Guidelines 2011.md,Ministry of Health Uganda,https://library.health.go.ug/file-download/dow...

In [ ]:
import pandas as pd

# Load datasets
qa_df = pd.read_json("/content/Evaluation_dataset_400.jsonl", lines=True)
ids_df = pd.read_json("/content/chunks_db_export.json")

print("QA shape:", qa_df.shape)
print("IDS shape:", ids_df.shape)

# Rename for clarity
ids_df = ids_df.rename(columns={"text": "context", "id": "true_chunk_id"})

# Merge on context text
merged = qa_df.merge(
    ids_df[["true_chunk_id", "context"]],
    on="context",
    how="left"
)

# Check how many failed to match
missing = merged["true_chunk_id"].isna().sum()
print("Missing IDs:", missing)

# Save final dataset
merged.to_json(
    "/content/Evaluation_dataset_400_with_ids.jsonl",
    orient="records",
    lines=True,
    force_ascii=False
)

merged.head()

QA shape: (400, 6)
IDS shape: (1931, 5)
Missing IDs: 0

,question,ground_truth,context,source_file,source_name,source_url,true_chunk_id
0,What is the current state of TB infection cont...,"At present, the knowledge and practice on TB i...","workers, children and other patients in these ...",Final TB Infection Control Guidelines 2011.md,Ministry of Health Uganda,https://library.health.go.ug/file-download/dow...,Final TB Infection Control Guidelines 2011.md_1
1,What is a landmark achievement in the fight ag...,The existence of this TB infection control gui...,tight work practices and being innovative. Hea...,Final TB Infection Control Guidelines 2011.md,Ministry of Health Uganda,https://library.health.go.ug/file-download/dow...,Final TB Infection Control Guidelines 2011.md_2
2,What is the name of the programme that provide...,Tuberculosis Control Assistance Programme (TBCAP),Regional Centre for Quality Health Care (RCQHC...,Final TB Infection Control Guidelines 2011.md,Ministry of Health Uganda,https://library.health.go.ug/file-download/dow...,Final TB Infection Control Guidelines 2011.md_3
3,What is the name of the Regional Centre for Qu...,Dr. Chilunga Puta,Dr Abel Nkolo National Professional Officer TB...,Final TB Infection Control Guidelines 2011.md,Ministry of Health Uganda,https://library.health.go.ug/file-download/dow...,Final TB Infection Control Guidelines 2011.md_4
4,What is the term for Multi Drug Resistant TB?,MDR-TB,Dr Juliana Nabatanzi NTLP-ZTLS South East Zone...,Final TB Infection Control Guidelines 2011.md,Ministry of Health Uganda,https://library.health.go.ug/file-download/dow...,Final TB Infection Control Guidelines 2011.md_5

In [ ]:
import json
import pandas as pd

qa_df = pd.read_json("/content/Evaluation_dataset_400_with_ids.jsonl", lines=True)
qa_df.head()

,question,ground_truth,context,source_file,source_name,source_url,true_chunk_id
0,What is the current state of TB infection cont...,"At present, the knowledge and practice on TB i...","workers, children and other patients in these ...",Final TB Infection Control Guidelines 2011.md,Ministry of Health Uganda,https://library.health.go.ug/file-download/dow...,Final TB Infection Control Guidelines 2011.md_1
1,What is a landmark achievement in the fight ag...,The existence of this TB infection control gui...,tight work practices and being innovative. Hea...,Final TB Infection Control Guidelines 2011.md,Ministry of Health Uganda,https://library.health.go.ug/file-download/dow...,Final TB Infection Control Guidelines 2011.md_2
2,What is the name of the programme that provide...,Tuberculosis Control Assistance Programme (TBCAP),Regional Centre for Quality Health Care (RCQHC...,Final TB Infection Control Guidelines 2011.md,Ministry of Health Uganda,https://library.health.go.ug/file-download/dow...,Final TB Infection Control Guidelines 2011.md_3
3,What is the name of the Regional Centre for Qu...,Dr. Chilunga Puta,Dr Abel Nkolo National Professional Officer TB...,Final TB Infection Control Guidelines 2011.md,Ministry of Health Uganda,https://library.health.go.ug/file-download/dow...,Final TB Infection Control Guidelines 2011.md_4
4,What is the term for Multi Drug Resistant TB?,MDR-TB,Dr Juliana Nabatanzi NTLP-ZTLS South East Zone...,Final TB Infection Control Guidelines 2011.md,Ministry of Health Uganda,https://library.health.go.ug/file-download/dow...,Final TB Infection Control Guidelines 2011.md_5

In [ ]:
qa_df.shape

(580, 7)

In [ ]:
qa_df.to_csv('Evaluation_dataset_400_with_ids.csv', index=False)

In [ ]:
import pandas as pd

df = pd.read_csv("eval_results.csv")

print("Recall@5:", df["recall_at_k"].mean())
print("MRR:", df["mrr"].mean())
print("Avg latency:", df["latency_sec"].mean())
print("Hit@5:", df["hit_at_k"].mean())

Recall@5: 0.5333333333333333
MRR: 0.2755555555555555
Avg latency: 6.116660865147908
Hit@5: 0.5333333333333333

In [ ]:
df.shape

(30, 9)

In [ ]:
df.head()

,question,true_chunk_id,retrieved_chunk_ids,recall_at_k,hit_at_k,mrr,latency_sec,num_sources,timestamp
0,What is the current state of TB infection cont...,Final TB Infection Control Guidelines 2011.md_1,"[""Final TB Infection Control Guidelines 2011.m...",1,1,0.2,6.793940,5,2026-03-01T19:36:57.469212
1,What is a landmark achievement in the fight ag...,Final TB Infection Control Guidelines 2011.md_2,"[""NTLP Manual 3rd edition_17th Aug_final.md_57...",0,0,0.0,10.088952,5,2026-03-01T19:37:10.569119
2,What is the name of the programme that provide...,Final TB Infection Control Guidelines 2011.md_3,"[""Final TB Infection Control Guidelines 2011.m...",0,0,0.0,6.416726,5,2026-03-01T19:37:19.991338
3,What is the name of the Regional Centre for Qu...,Final TB Infection Control Guidelines 2011.md_4,"[""Final TB Infection Control Guidelines 2011.m...",1,1,0.5,4.264942,5,2026-03-01T19:37:27.261947
4,What is the term for Multi Drug Resistant TB?,Final TB Infection Control Guidelines 2011.md_5,"[""Global tuberculosis report 2024.md_231"", ""TB...",0,0,0.0,4.805703,5,2026-03-01T19:37:35.072534

In [ ]:
df.describe()

       recall_at_k   hit_at_k        mrr  latency_sec  num_sources
count    30.000000  30.000000  30.000000    30.000000         30.0
mean      0.533333   0.533333   0.275556     6.116661          5.0
std       0.507416   0.507416   0.344378     1.846562          0.0
min       0.000000   0.000000   0.000000     3.821364          5.0
25%       0.000000   0.000000   0.000000     4.787133          5.0
50%       1.000000   1.000000   0.200000     5.711560          5.0
75%       1.000000   1.000000   0.500000     6.954709          5.0
max       1.000000   1.000000   1.000000    11.022712          5.0

In [ ]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
recall_at_k,30.0,0.533333,0.507416,0.000000,0.000000,1.00000,1.000000,1.000000
hit_at_k,30.0,0.533333,0.507416,0.000000,0.000000,1.00000,1.000000,1.000000
mrr,30.0,0.275556,0.344378,0.000000,0.000000,0.20000,0.500000,1.000000
latency_sec,30.0,6.116661,1.846562,3.821364,4.787133,5.71156,6.954709,11.022712
num_sources,30.0,5.000000,0.000000,5.000000,5.000000,5.00000,5.000000,5.000000

In [ ]:
df[df["recall_at_k"] == 0][["question", "true_chunk_id", "retrieved_chunk_ids"]].head(5)

,question,true_chunk_id,retrieved_chunk_ids
1,What is a landmark achievement in the fight ag...,Final TB Infection Control Guidelines 2011.md_2,"[""NTLP Manual 3rd edition_17th Aug_final.md_57..."
2,What is the name of the programme that provide...,Final TB Infection Control Guidelines 2011.md_3,"[""Final TB Infection Control Guidelines 2011.m..."
4,What is the term for Multi Drug Resistant TB?,Final TB Infection Control Guidelines 2011.md_5,"[""Global tuberculosis report 2024.md_231"", ""TB..."
7,What is the association of Tuberculosis (TB) w...,Final TB Infection Control Guidelines 2011.md_10,"[""NTLP Manual 3rd edition_17th Aug_final.md_55..."
8,What settings are considered high-risk for tra...,Final TB Infection Control Guidelines 2011.md_11,"[""Final TB Infection Control Guidelines 2011.m..."

In [ ]:
!pip install rouge-score bert-score

Collecting rouge-score
  Downloading rouge_score-0.1.2.tar.gz (17 kB)
  Preparing metadata (setup.py) ... done
Collecting bert-score
  Downloading bert_score-0.3.13-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from rouge-score) (1.4.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (from rouge-score) (3.9.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from rouge-score) (2.0.2)
Requirement already satisfied: six>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from rouge-score) (1.17.0)
Requirement already satisfied: torch>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from bert-score) (2.10.0+cu128)
Requirement already satisfied: pandas>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from bert-score) (2.2.2)
Requirement already satisfied: transformers>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from bert-score) (5.0.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from bert-score) (2.32.4)
Requirement already satisfied: tqdm>=4.31.1 in /usr/local/lib/python3.12/dist-packages (from bert-score) (4.67.3)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from bert-score) (3.10.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from bert-score) (26.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.1->bert-score) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.1->bert-score) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.1->bert-score) (2025.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (3.24.3)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (2025.3.0)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=1.0.0->bert-score) (1.3.5)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=3.0.0->bert-score) (1.4.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers>=3.0.0->bert-score) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers>=3.0.0->bert-score) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=3.0.0->bert-score) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers>=3.0.0->bert-score) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers>=3.0.0->bert-score) (0.7.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert-score) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert-score) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert-score) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert-score) (1.4.9)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert-score) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert-score) (3.3.2)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk->rouge-score) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk->rouge-score) (1.5.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->bert-score) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->bert-score) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->bert-score) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->bert-score) (2026.1.4)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert-score) (1.3.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert-score) (0.28.1)
Requirement already satisfied: shellingham in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert-score) (1.5.4)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.0.0->bert-score) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.0.0->bert-score) (3.0.3)
Requirement already satisfied: typer>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from typer-slim->transformers>=3.0.0->bert-score) (0.24.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert-score) (4.12.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert-score) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert-score) (0.16.0)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->transformers>=3.0.0->bert-score) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->transformers>=3.0.0->bert-score) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim->transformers>=3.0.0->bert-score) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim->transformers>=3.0.0->bert-score) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer>=0.24.0->typer-slim->transformers>=3.0.0->bert-score) (0.1.2)
Downloading bert_score-0.3.13-py3-none-any.whl (61 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.1/61.1 kB 5.0 MB/s eta 0:00:00
Building wheels for collected packages: rouge-score
  Building wheel for rouge-score (setup.py) ... done
  Created wheel for rouge-score: filename=rouge_score-0.1.2-py3-none-any.whl size=24934 sha256=a887bbac972eb47a3054783f14c9e3edb3009bc10020f22cd9ee470c3041a6dd
  Stored in directory: /root/.cache/pip/wheels/85/9d/af/01feefbe7d55ef5468796f0c68225b6788e85d9d0a281e7a70
Successfully built rouge-score
Installing collected packages: rouge-score, bert-score
Successfully installed bert-score-0.3.13 rouge-score-0.1.2

In [ ]:
import pandas as pd
from rouge_score import rouge_scorer
from bert_score import score as bertscore

# Load results
df = pd.read_csv("eval_results.csv")

# Load the original QA dataset to get the ground_truth and answer columns
qa_df = pd.read_json("/content/Evaluation_dataset_400_with_ids.jsonl", lines=True)

# Merge ground_truth and answer from qa_df into df using 'question' as the key
df = df.merge(qa_df[['question', 'ground_truth']], on='question', how='left')

# Initialize ROUGE
scorer = rouge_scorer.RougeScorer(["rouge1", "rouge2", "rougeL"], use_stemmer=True)

rouge1_list = []
rouge2_list = []
rougeL_list = []

for gt, ans in zip(df["ground_truth"], df["answer"]):
    if pd.isna(ans):
        rouge1_list.append(0)
        rouge2_list.append(0)
        rougeL_list.append(0)
        continue

    scores = scorer.score(gt, ans)
    rouge1_list.append(scores["rouge1"].fmeasure)
    rouge2_list.append(scores["rouge2"].fmeasure)
    rougeL_list.append(scores["rougeL"].fmeasure)

df["rouge1"] = rouge1_list
df["rouge2"] = rouge2_list
df["rougeL"] = rougeL_list

# -------- BERTScore --------
P, R, F1 = bertscore(
    df["answer"].fillna("").tolist(),
    df["ground_truth"].fillna("").tolist(),
    lang="en",
    model_type="microsoft/deberta-xlarge-mnli"  # strong semantic model
)

df["bertscore_precision"] = P.tolist()
df["bertscore_recall"] = R.tolist()
df["bertscore_f1"] = F1.tolist()

# Save new file
df.to_csv("eval_results_with_generation_metrics.csv", index=False)

print("ROUGE-1:", df["rouge1"].mean())
print("ROUGE-2:", df["rouge2"].mean())
print("ROUGE-L:", df["rougeL"].mean())
print("BERTScore F1:", df["bertscore_f1"].mean())

KeyError: 'answer'

In [ ]:
import requests
import pandas as pd
import time
import json
from tqdm import tqdm
from math import log2
from rouge_score import rouge_scorer
from bert_score import score as bertscore
from datetime import datetime
import os

# ================= CONFIG =================

API_URL = "https://helpcentre-dsi-mdr.emergentai.ug/chat"  # remote endpoint
INPUT_CSV = "Evaluation_dataset_400_with_ids.csv"
OUTPUT_CSV = "eval_results_full_remote.csv"

TOP_K = 5
MAX_QUESTIONS = 50
SLEEP_SEC = 2
TIMEOUT = 60
MAX_RETRIES = 3

# ================= METRIC FUNCTIONS =================

def precision_at_k(relevant, retrieved, k):
    return len(set(relevant) & set(retrieved[:k])) / k if k > 0 else 0

def recall_at_k(relevant, retrieved, k):
    return len(set(relevant) & set(retrieved[:k])) / len(relevant) if relevant else 0

def hit_at_k(relevant, retrieved, k):
    return 1 if len(set(relevant) & set(retrieved[:k])) > 0 else 0

def mrr_at_k(relevant, retrieved, k):
    for i, doc in enumerate(retrieved[:k]):
        if doc in relevant:
            return 1 / (i + 1)
    return 0

def ndcg_at_k(relevant, retrieved, k):
    dcg = sum(1/log2(i+2) for i, d in enumerate(retrieved[:k]) if d in relevant)
    idcg = sum(1/log2(i+2) for i in range(min(len(relevant), k)))
    return dcg/idcg if idcg > 0 else 0

def ap_at_k(relevant, retrieved, k):
    hits = 0
    score = 0
    for i, d in enumerate(retrieved[:k]):
        if d in relevant:
            hits += 1
            score += hits/(i+1)
    return score/len(relevant) if relevant else 0

# ================= LOAD DATA =================

df = pd.read_csv(INPUT_CSV).head(MAX_QUESTIONS)

# Resume support
if os.path.exists(OUTPUT_CSV):
    done_df = pd.read_csv(OUTPUT_CSV)
    done_questions = set(done_df["question"])
else:
    done_df = pd.DataFrame()
    done_questions = set()

scorer = rouge_scorer.RougeScorer(["rouge1","rouge2","rougeL"], use_stemmer=True)

# ================= MAIN LOOP =================

for _, row in tqdm(df.iterrows(), total=len(df)):

    question = row["question"]
    gt_answer = str(row["ground_truth"])
    true_chunk = row["true_chunk_id"]

    if question in done_questions:
        continue

    payload = {"query": question}

    retries = 0
    success = False

    while retries < MAX_RETRIES and not success:
        try:
            start = time.time()
            r = requests.post(API_URL, json=payload, timeout=TIMEOUT)
            latency = time.time() - start

            if r.status_code != 200:
                raise RuntimeError(f"HTTP {r.status_code}")

            data = r.json()
            success = True

        except Exception as e:
            retries += 1
            print(f"⚠️ Retry {retries}/{MAX_RETRIES} for question: {question}")
            print(e)
            time.sleep(2)

    if not success:
        result = {
            "question": question,
            "true_chunk_id": true_chunk,
            "retrieved_chunk_ids": "[]",
            "precision@5": 0,
            "recall@5": 0,
            "hit@5": 0,
            "mrr@5": 0,
            "ndcg@5": 0,
            "map@5": 0,
            "rouge1": 0,
            "rouge2": 0,
            "rougeL": 0,
            "bertscore_f1": 0,
            "latency_sec": None,
            "status": "failed",
            "timestamp": datetime.utcnow().isoformat()
        }
        pd.DataFrame([result]).to_csv(
            OUTPUT_CSV, mode="a", index=False,
            header=not os.path.exists(OUTPUT_CSV)
        )
        continue

    answer = data.get("answer","")
    sources = data.get("sources", [])

    # Extract retrieved chunk IDs safely
    retrieved_ids = []
    for s in sources:
        if isinstance(s, dict) and "doc_id" in s:
            retrieved_ids.append(s["doc_id"])

    relevant = [true_chunk]

    # ===== Retriever metrics =====
    p5 = precision_at_k(relevant, retrieved_ids, TOP_K)
    r5 = recall_at_k(relevant, retrieved_ids, TOP_K)
    hit5 = hit_at_k(relevant, retrieved_ids, TOP_K)
    mrr5 = mrr_at_k(relevant, retrieved_ids, TOP_K)
    ndcg5 = ndcg_at_k(relevant, retrieved_ids, TOP_K)
    map5 = ap_at_k(relevant, retrieved_ids, TOP_K)

    # ===== Generator metrics =====
    rouge_scores = scorer.score(gt_answer, answer)
    rouge1 = rouge_scores["rouge1"].fmeasure
    rouge2 = rouge_scores["rouge2"].fmeasure
    rougeL = rouge_scores["rougeL"].fmeasure

    try:
        P, R, F1 = bertscore([answer], [gt_answer], lang="en", model_type="microsoft/deberta-xlarge-mnli")
        bert_f1 = F1.item()
    except:
        bert_f1 = 0

    result = {
        "question": question,
        "true_chunk_id": true_chunk,
        "retrieved_chunk_ids": json.dumps(retrieved_ids),
        "precision@5": p5,
        "recall@5": r5,
        "hit@5": hit5,
        "mrr@5": mrr5,
        "ndcg@5": ndcg5,
        "map@5": map5,
        "rouge1": rouge1,
        "rouge2": rouge2,
        "rougeL": rougeL,
        "bertscore_f1": bert_f1,
        "latency_sec": latency,
        "status": "ok",
        "timestamp": datetime.utcnow().isoformat()
    }

    pd.DataFrame([result]).to_csv(
        OUTPUT_CSV, mode="a", index=False,
        header=not os.path.exists(OUTPUT_CSV)
    )

    time.sleep(SLEEP_SEC)

print("✅ Evaluation complete.")

  0%|          | 0/50 [00:00<?, ?it/s]/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/792 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/52.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

pytorch_model.bin:   0%|          | 0.00/3.04G [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/3.04G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
/tmp/ipykernel_322/2585020300.py:175: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  "timestamp": datetime.utcnow().isoformat()
  2%|▏         | 1/50 [01:29<1:12:56, 89.31s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
  4%|▍         | 2/50 [02:16<51:25, 64.28s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
  6%|▌         | 3/50 [02:49<39:15, 50.12s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
  8%|▊         | 4/50 [03:19<32:26, 42.31s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 10%|█         | 5/50 [03:50<28:39, 38.22s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 12%|█▏        | 6/50 [04:25<27:09, 37.04s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 14%|█▍        | 7/50 [05:00<26:09, 36.51s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 16%|█▌        | 8/50 [05:34<24:50, 35.49s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 18%|█▊        | 9/50 [06:07<23:44, 34.74s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 20%|██        | 10/50 [06:38<22:21, 33.53s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 22%|██▏       | 11/50 [07:10<21:36, 33.23s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 24%|██▍       | 12/50 [07:43<20:55, 33.04s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 26%|██▌       | 13/50 [08:15<20:09, 32.69s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 28%|██▊       | 14/50 [08:47<19:29, 32.49s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 30%|███       | 15/50 [09:20<19:03, 32.68s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 32%|███▏      | 16/50 [09:53<18:35, 32.81s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 34%|███▍      | 17/50 [10:26<18:10, 33.04s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 36%|███▌      | 18/50 [11:00<17:43, 33.23s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 38%|███▊      | 19/50 [11:32<16:55, 32.74s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 40%|████      | 20/50 [12:06<16:36, 33.21s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 42%|████▏     | 21/50 [12:38<15:53, 32.87s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 44%|████▍     | 22/50 [13:09<15:07, 32.42s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 46%|████▌     | 23/50 [13:42<14:36, 32.47s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 48%|████▊     | 24/50 [14:15<14:05, 32.50s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 50%|█████     | 25/50 [14:46<13:27, 32.32s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 52%|█████▏    | 26/50 [15:16<12:37, 31.58s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 54%|█████▍    | 27/50 [15:49<12:15, 31.98s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 56%|█████▌    | 28/50 [16:20<11:35, 31.63s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 58%|█████▊    | 29/50 [16:54<11:19, 32.36s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 60%|██████    | 30/50 [17:27<10:48, 32.44s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 62%|██████▏   | 31/50 [18:07<11:00, 34.78s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 64%|██████▍   | 32/50 [18:39<10:11, 33.96s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 66%|██████▌   | 33/50 [19:10<09:24, 33.21s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 68%|██████▊   | 34/50 [19:44<08:51, 33.23s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 70%|███████   | 35/50 [20:16<08:15, 33.06s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 72%|███████▏  | 36/50 [20:49<07:40, 32.87s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 74%|███████▍  | 37/50 [21:19<06:57, 32.10s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 76%|███████▌  | 38/50 [21:49<06:16, 31.36s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 78%|███████▊  | 39/50 [22:22<05:51, 31.93s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 80%|████████  | 40/50 [22:54<05:18, 31.83s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 82%|████████▏ | 41/50 [23:24<04:41, 31.29s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 84%|████████▍ | 42/50 [23:55<04:09, 31.20s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 86%|████████▌ | 43/50 [24:29<03:45, 32.16s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 88%|████████▊ | 44/50 [25:04<03:18, 33.13s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 90%|█████████ | 45/50 [25:33<02:38, 31.73s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 92%|█████████▏| 46/50 [25:48<01:47, 26.76s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 94%|█████████▍| 47/50 [25:59<01:06, 22.03s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 96%|█████████▌| 48/50 [26:09<00:36, 18.36s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 98%|█████████▊| 49/50 [26:19<00:16, 16.03s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
100%|██████████| 50/50 [26:32<00:00, 31.84s/it]

✅ Evaluation complete.

In [ ]:
df = pd.read_csv("eval_results_full_remote.csv")

print("Recall@5:", df["recall@5"].mean())
print("MRR@5:", df["mrr@5"].mean())
print("NDCG@5:", df["ndcg@5"].mean())
print("MAP@5:", df["map@5"].mean())
print("ROUGE-L:", df["rougeL"].mean())
print("BERTScore:", df["bertscore_f1"].mean())
print("Latency:", df["latency_sec"].mean())

Recall@5: 0.64
MRR@5: 0.39433333333333337
NDCG@5: 0.455118983563171
MAP@5: 0.39433333333333337
ROUGE-L: 0.15251799686529385
BERTScore: 0.0
Latency: 5.770116901397705

In [ ]:
!pip install rouge-score bert-score

Collecting rouge-score
  Downloading rouge_score-0.1.2.tar.gz (17 kB)
  Preparing metadata (setup.py) ... done
Collecting bert-score
  Downloading bert_score-0.3.13-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from rouge-score) (1.4.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (from rouge-score) (3.9.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from rouge-score) (2.0.2)
Requirement already satisfied: six>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from rouge-score) (1.17.0)
Requirement already satisfied: torch>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from bert-score) (2.10.0+cpu)
Requirement already satisfied: pandas>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from bert-score) (2.2.2)
Requirement already satisfied: transformers>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from bert-score) (5.0.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from bert-score) (2.32.4)
Requirement already satisfied: tqdm>=4.31.1 in /usr/local/lib/python3.12/dist-packages (from bert-score) (4.67.3)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from bert-score) (3.10.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from bert-score) (26.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.1->bert-score) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.1->bert-score) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.1->bert-score) (2025.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (3.24.3)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert-score) (2025.3.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=3.0.0->bert-score) (1.5.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers>=3.0.0->bert-score) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers>=3.0.0->bert-score) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=3.0.0->bert-score) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers>=3.0.0->bert-score) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers>=3.0.0->bert-score) (0.7.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert-score) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert-score) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert-score) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert-score) (1.4.9)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert-score) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert-score) (3.3.2)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk->rouge-score) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk->rouge-score) (1.5.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->bert-score) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->bert-score) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->bert-score) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->bert-score) (2026.2.25)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert-score) (1.3.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert-score) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert-score) (0.24.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.0.0->bert-score) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.0.0->bert-score) (3.0.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert-score) (4.12.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert-score) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert-score) (0.16.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert-score) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert-score) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert-score) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert-score) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert-score) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers>=3.0.0->bert-score) (0.1.2)
Downloading bert_score-0.3.13-py3-none-any.whl (61 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.1/61.1 kB 3.2 MB/s eta 0:00:00
Building wheels for collected packages: rouge-score
  Building wheel for rouge-score (setup.py) ... done
  Created wheel for rouge-score: filename=rouge_score-0.1.2-py3-none-any.whl size=24934 sha256=e88e42c7fbff89af7297c423bbdd3bb0a36c9555c8c933e1f82f304aa34e405a
  Stored in directory: /root/.cache/pip/wheels/85/9d/af/01feefbe7d55ef5468796f0c68225b6788e85d9d0a281e7a70
Successfully built rouge-score
Installing collected packages: rouge-score, bert-score
Successfully installed bert-score-0.3.13 rouge-score-0.1.2

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv("/content/Evaluation_dataset_400_with_ids.csv")
df.head()

,question,ground_truth,context,source_file,source_name,source_url,true_chunk_id
0,What is the current state of TB infection cont...,"At present, the knowledge and practice on TB i...","workers, children and other patients in these ...",Final TB Infection Control Guidelines 2011.md,Ministry of Health Uganda,https://library.health.go.ug/file-download/dow...,Final TB Infection Control Guidelines 2011.md_1
1,What is a landmark achievement in the fight ag...,The existence of this TB infection control gui...,tight work practices and being innovative. Hea...,Final TB Infection Control Guidelines 2011.md,Ministry of Health Uganda,https://library.health.go.ug/file-download/dow...,Final TB Infection Control Guidelines 2011.md_2
2,What is the name of the programme that provide...,Tuberculosis Control Assistance Programme (TBCAP),Regional Centre for Quality Health Care (RCQHC...,Final TB Infection Control Guidelines 2011.md,Ministry of Health Uganda,https://library.health.go.ug/file-download/dow...,Final TB Infection Control Guidelines 2011.md_3
3,What is the name of the Regional Centre for Qu...,Dr. Chilunga Puta,Dr Abel Nkolo National Professional Officer TB...,Final TB Infection Control Guidelines 2011.md,Ministry of Health Uganda,https://library.health.go.ug/file-download/dow...,Final TB Infection Control Guidelines 2011.md_4
4,What is the term for Multi Drug Resistant TB?,MDR-TB,Dr Juliana Nabatanzi NTLP-ZTLS South East Zone...,Final TB Infection Control Guidelines 2011.md,Ministry of Health Uganda,https://library.health.go.ug/file-download/dow...,Final TB Infection Control Guidelines 2011.md_5

In [ ]:
import requests
import pandas as pd
import time
import json
from tqdm import tqdm
from math import log2
from rouge_score import rouge_scorer
from bert_score import score as bertscore
from datetime import datetime
import os

# ================= CONFIG =================

API_URL = "https://helpcentre-dsi-mdr.emergentai.ug/chat"
INPUT_CSV = "Evaluation_dataset_400_with_ids.csv"
OUTPUT_CSV = "Eval_results_full_set_50.csv"

TOP_K = 5
MAX_QUESTIONS = 50
SLEEP_SEC = 2
TIMEOUT = 60
MAX_RETRIES = 3

# ================= METRIC FUNCTIONS =================

def precision_at_k(relevant, retrieved, k):
    return len(set(relevant) & set(retrieved[:k])) / k if k > 0 else 0

def recall_at_k(relevant, retrieved, k):
    return len(set(relevant) & set(retrieved[:k])) / len(relevant) if relevant else 0

def hit_at_k(relevant, retrieved, k):
    return 1 if len(set(relevant) & set(retrieved[:k])) > 0 else 0

def mrr_at_k(relevant, retrieved, k):
    for i, doc in enumerate(retrieved[:k]):
        if doc in relevant:
            return 1 / (i + 1)
    return 0

def ndcg_at_k(relevant, retrieved, k):
    dcg = sum(1/log2(i+2) for i, d in enumerate(retrieved[:k]) if d in relevant)
    idcg = sum(1/log2(i+2) for i in range(min(len(relevant), k)))
    return dcg/idcg if idcg > 0 else 0

def ap_at_k(relevant, retrieved, k):
    hits = 0
    score = 0
    for i, d in enumerate(retrieved[:k]):
        if d in relevant:
            hits += 1
            score += hits/(i+1)
    return score/len(relevant) if relevant else 0

# ================= LOAD DATA =================

df = pd.read_csv(INPUT_CSV)

# limit evaluation size
df = df.head(MAX_QUESTIONS)

# Resume support
if os.path.exists(OUTPUT_CSV):
    done_df = pd.read_csv(OUTPUT_CSV)
    done_questions = set(done_df["question"])
else:
    done_questions = set()

# ROUGE scorer
scorer = rouge_scorer.RougeScorer(["rouge1","rouge2","rougeL"], use_stemmer=True)

# ================= MAIN LOOP =================

for _, row in tqdm(df.iterrows(), total=len(df)):

    question = row["question"]
    gt_answer = str(row["ground_truth"])
    true_chunk = row["true_chunk_id"]

    if question in done_questions:
        continue

    payload = {"query": question}

    retries = 0
    success = False
    latency = None
    answer = ""
    retrieved_ids = []

    while retries < MAX_RETRIES and not success:
        try:
            start = time.time()

            r = requests.post(
                API_URL,
                json=payload,
                timeout=TIMEOUT
            )

            latency = time.time() - start

            if r.status_code != 200:
                raise RuntimeError(f"HTTP {r.status_code}")

            data = r.json()
            success = True

        except Exception as e:
            retries += 1
            print(f"Retry {retries}/{MAX_RETRIES} for question:")
            print(question)
            print(e)
            time.sleep(2)

    # ================= HANDLE FAILURE =================

    if not success:

        result = {
            "question": question,
            "true_chunk_id": true_chunk,
            "ground_truth": gt_answer,
            "answer": "",
            "retrieved_chunk_ids": "[]",
            "precision@5": 0,
            "recall@5": 0,
            "hit@5": 0,
            "mrr@5": 0,
            "ndcg@5": 0,
            "map@5": 0,
            "rouge1": 0,
            "rouge2": 0,
            "rougeL": 0,
            "bertscore_f1": 0,
            "latency_sec": None,
            "status": "failed",
            "timestamp": datetime.utcnow().isoformat()
        }

        pd.DataFrame([result]).to_csv(
            OUTPUT_CSV,
            mode="a",
            index=False,
            header=not os.path.exists(OUTPUT_CSV)
        )

        continue

    # ================= PARSE RESPONSE =================

    answer = data.get("answer", "")
    sources = data.get("sources", [])

    # Extract retrieved chunk IDs safely
    for s in sources:
        if isinstance(s, dict) and "doc_id" in s:
            retrieved_ids.append(s["doc_id"])

    relevant = [true_chunk]

    # ================= RETRIEVER METRICS =================

    p5 = precision_at_k(relevant, retrieved_ids, TOP_K)
    r5 = recall_at_k(relevant, retrieved_ids, TOP_K)
    hit5 = hit_at_k(relevant, retrieved_ids, TOP_K)
    mrr5 = mrr_at_k(relevant, retrieved_ids, TOP_K)
    ndcg5 = ndcg_at_k(relevant, retrieved_ids, TOP_K)
    map5 = ap_at_k(relevant, retrieved_ids, TOP_K)

    # ================= GENERATOR METRICS =================

    rouge_scores = scorer.score(gt_answer, answer)

    rouge1 = rouge_scores["rouge1"].fmeasure
    rouge2 = rouge_scores["rouge2"].fmeasure
    rougeL = rouge_scores["rougeL"].fmeasure

    try:
        P, R, F1 = bertscore(
            [answer],
            [gt_answer],
            lang="en",
            model_type="microsoft/deberta-xlarge-mnli"
        )

        bert_f1 = F1.item()

    except:
        bert_f1 = 0

    # ================= SAVE RESULT =================

    result = {
        "question": question,
        "true_chunk_id": true_chunk,
        "ground_truth": gt_answer,
        "answer": answer,
        "retrieved_chunk_ids": json.dumps(retrieved_ids),
        "precision@5": p5,
        "recall@5": r5,
        "hit@5": hit5,
        "mrr@5": mrr5,
        "ndcg@5": ndcg5,
        "map@5": map5,
        "rouge1": rouge1,
        "rouge2": rouge2,
        "rougeL": rougeL,
        "bertscore_f1": bert_f1,
        "latency_sec": latency,
        "status": "ok",
        "timestamp": datetime.utcnow().isoformat()
    }

    pd.DataFrame([result]).to_csv(
        OUTPUT_CSV,
        mode="a",
        index=False,
        header=not os.path.exists(OUTPUT_CSV)
    )

    time.sleep(SLEEP_SEC)

print("Evaluation complete.")

  0%|          | 0/50 [00:00<?, ?it/s]/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/792 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

tokenizer_config.json:   0%|          | 0.00/52.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

pytorch_model.bin:   0%|          | 0.00/3.04G [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/3.04G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
/tmp/ipykernel_253/25113438.py:212: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  "timestamp": datetime.utcnow().isoformat()
  2%|▏         | 1/50 [01:46<1:27:16, 106.87s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
  4%|▍         | 2/50 [02:10<46:31, 58.16s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
  6%|▌         | 3/50 [02:37<34:15, 43.72s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
  8%|▊         | 4/50 [03:01<27:29, 35.87s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 10%|█         | 5/50 [03:25<23:46, 31.70s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 12%|█▏        | 6/50 [03:50<21:32, 29.37s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 14%|█▍        | 7/50 [04:17<20:25, 28.51s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 16%|█▌        | 8/50 [04:46<20:12, 28.87s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 18%|█▊        | 9/50 [05:11<18:47, 27.51s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 20%|██        | 10/50 [05:36<17:55, 26.89s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 22%|██▏       | 11/50 [06:03<17:28, 26.88s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 24%|██▍       | 12/50 [06:17<14:28, 22.85s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 26%|██▌       | 13/50 [06:33<12:46, 20.72s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 28%|██▊       | 14/50 [06:46<11:05, 18.49s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 30%|███       | 15/50 [07:00<09:57, 17.07s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 32%|███▏      | 16/50 [07:11<08:43, 15.40s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 34%|███▍      | 17/50 [07:30<08:58, 16.31s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 36%|███▌      | 18/50 [07:44<08:23, 15.73s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 38%|███▊      | 19/50 [07:56<07:35, 14.68s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 40%|████      | 20/50 [08:12<07:27, 14.93s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 42%|████▏     | 21/50 [08:22<06:30, 13.48s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 44%|████▍     | 22/50 [08:36<06:22, 13.66s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 46%|████▌     | 23/50 [08:49<06:05, 13.53s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 48%|████▊     | 24/50 [09:04<06:01, 13.92s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 50%|█████     | 25/50 [09:16<05:34, 13.40s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 52%|█████▏    | 26/50 [09:32<05:37, 14.05s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 54%|█████▍    | 27/50 [09:45<05:15, 13.73s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 56%|█████▌    | 28/50 [09:56<04:43, 12.90s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 58%|█████▊    | 29/50 [10:09<04:34, 13.07s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 60%|██████    | 30/50 [10:21<04:14, 12.74s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 62%|██████▏   | 31/50 [10:40<04:36, 14.58s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 64%|██████▍   | 32/50 [10:53<04:14, 14.15s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 66%|██████▌   | 33/50 [11:07<03:59, 14.08s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 68%|██████▊   | 34/50 [11:22<03:46, 14.17s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 70%|███████   | 35/50 [11:35<03:30, 14.04s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 72%|███████▏  | 36/50 [11:47<03:06, 13.30s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 74%|███████▍  | 37/50 [12:01<02:54, 13.46s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 76%|███████▌  | 38/50 [12:12<02:33, 12.81s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 78%|███████▊  | 39/50 [12:32<02:44, 14.91s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 80%|████████  | 40/50 [13:04<03:20, 20.09s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 82%|████████▏ | 41/50 [13:25<03:04, 20.52s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 84%|████████▍ | 42/50 [13:46<02:44, 20.58s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 86%|████████▌ | 43/50 [14:11<02:31, 21.71s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 88%|████████▊ | 44/50 [14:29<02:04, 20.71s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 90%|█████████ | 45/50 [14:53<01:49, 21.82s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 92%|█████████▏| 46/50 [15:12<01:23, 20.81s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 94%|█████████▍| 47/50 [15:31<01:00, 20.24s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 96%|█████████▌| 48/50 [15:46<00:37, 18.81s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
 98%|█████████▊| 49/50 [16:18<00:22, 22.71s/it]

Loading weights:   0%|          | 0/772 [00:00<?, ?it/s]

DebertaModel LOAD REPORT from: microsoft/deberta-xlarge-mnli
Key                 | Status     |  |
--------------------+------------+--+-
classifier.bias     | UNEXPECTED |  |
pooler.dense.bias   | UNEXPECTED |  |
classifier.weight   | UNEXPECTED |  |
pooler.dense.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
100%|██████████| 50/50 [16:35<00:00, 19.90s/it]

Evaluation complete.

In [ ]:
import pandas as pd

# Load evaluation results
df = pd.read_csv("Eval_results_full_set_50.csv")

print("\n===== RAG SYSTEM EVALUATION RESULTS =====\n")

print("Retriever Metrics")
print("------------------")
print("Precision@5 :", df["precision@5"].mean())
print("Recall@5    :", df["recall@5"].mean())
print("Hit@5       :", df["hit@5"].mean())
print("MRR@5       :", df["mrr@5"].mean())
print("NDCG@5      :", df["ndcg@5"].mean())
print("MAP@5       :", df["map@5"].mean())

print("\nGenerator Metrics")
print("------------------")
print("ROUGE-L     :", df["rougeL"].mean())
print("BERTScore   :", df["bertscore_f1"].mean())

print("\nSystem Metrics")
print("------------------")
print("Average Latency (sec):", df["latency_sec"].mean())

print("\nTotal Questions Evaluated:", len(df))

===== RAG SYSTEM EVALUATION RESULTS =====

Retriever Metrics
------------------
Precision@5 : 0.12800000000000003
Recall@5    : 0.64
Hit@5       : 0.64
MRR@5       : 0.39433333333333337
NDCG@5      : 0.455118983563171
MAP@5       : 0.39433333333333337

Generator Metrics
------------------
ROUGE-L     : 0.16384211177457536
BERTScore   : 0.0

System Metrics
------------------
Average Latency (sec): 6.1116811609268185

Total Questions Evaluated: 50

In [ ]:
import pandas as pd

df = pd.read_csv("Eval_results_full_set_50.csv")

In [ ]:
df.head()

,question,true_chunk_id,ground_truth,answer,retrieved_chunk_ids,precision@5,recall@5,hit@5,mrr@5,ndcg@5,map@5,rouge1,rouge2,rougeL,bertscore_f1,latency_sec,status,timestamp
0,What is the current state of TB infection cont...,Final TB Infection Control Guidelines 2011.md_1,"At present, the knowledge and practice on TB i...","According to the provided information, the cur...","[""Final TB Infection Control Guidelines 2011.m...",0.2,1.0,1,0.2,0.386853,0.2,0.285714,0.276730,0.285714,0,10.782317,ok,2026-03-08T15:47:27.580553
1,What is a landmark achievement in the fight ag...,Final TB Infection Control Guidelines 2011.md_2,The existence of this TB infection control gui...,"According to the provided information, a landm...","[""NTLP Manual 3rd edition_17th Aug_final.md_57...",0.0,0.0,0,0.0,0.000000,0.0,0.057554,0.000000,0.057554,0,8.269862,ok,2026-03-08T15:47:51.674992
2,What is the name of the programme that provide...,Final TB Infection Control Guidelines 2011.md_3,Tuberculosis Control Assistance Programme (TBCAP),The provided information does not explicitly s...,"[""Final TB Infection Control Guidelines 2011.m...",0.0,0.0,0,0.0,0.000000,0.0,0.055046,0.018692,0.055046,0,8.753474,ok,2026-03-08T15:48:18.210225
3,What is the name of the Regional Centre for Qu...,Final TB Infection Control Guidelines 2011.md_4,Dr. Chilunga Puta,"According to the provided information, the nam...","[""Final TB Infection Control Guidelines 2011.m...",0.2,1.0,1,0.5,0.630930,0.5,0.000000,0.000000,0.000000,0,5.172339,ok,2026-03-08T15:48:42.023961
4,What is the term for Multi Drug Resistant TB?,Final TB Infection Control Guidelines 2011.md_5,MDR-TB,Multidrug-resistant TB (MDR-TB) is defined as ...,"[""Global tuberculosis report 2024.md_231"", ""TB...",0.0,0.0,0,0.0,0.000000,0.0,0.047059,0.024096,0.047059,0,6.062001,ok,2026-03-08T15:49:06.331142

In [ ]:
!pip install ragas

Collecting ragas
  Downloading ragas-0.4.3-py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: numpy<3.0.0,>=1.21.0 in /usr/local/lib/python3.12/dist-packages (from ragas) (2.0.2)
Requirement already satisfied: datasets>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from ragas) (4.0.0)
Requirement already satisfied: tiktoken in /usr/local/lib/python3.12/dist-packages (from ragas) (0.12.0)
Requirement already satisfied: pydantic>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from ragas) (2.12.3)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.12/dist-packages (from ragas) (1.6.0)
Collecting appdirs (from ragas)
  Downloading appdirs-1.4.4-py2.py3-none-any.whl.metadata (9.0 kB)
Collecting diskcache>=5.6.3 (from ragas)
  Downloading diskcache-5.6.3-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from ragas) (0.24.1)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from ragas) (13.9.4)
Requirement already satisfied: openai>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from ragas) (2.24.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from ragas) (4.67.3)
Collecting instructor (from ragas)
  Downloading instructor-1.14.5-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: pillow>=10.4.0 in /usr/local/lib/python3.12/dist-packages (from ragas) (11.3.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from ragas) (3.6.1)
Collecting scikit-network (from ragas)
  Downloading scikit_network-0.33.5-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.5 kB)
Requirement already satisfied: langchain in /usr/local/lib/python3.12/dist-packages (from ragas) (1.2.10)
Requirement already satisfied: langchain-core in /usr/local/lib/python3.12/dist-packages (from ragas) (1.2.16)
Collecting langchain-community (from ragas)
  Downloading langchain_community-0.4.1-py3-none-any.whl.metadata (3.0 kB)
Collecting langchain_openai (from ragas)
  Downloading langchain_openai-1.1.10-py3-none-any.whl.metadata (3.1 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=4.0.0->ragas) (3.24.3)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.0.0->ragas) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.0.0->ragas) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets>=4.0.0->ragas) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.0.0->ragas) (2.32.4)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets>=4.0.0->ragas) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.0.0->ragas) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=4.0.0->ragas) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.0.0->ragas) (1.5.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets>=4.0.0->ragas) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.0.0->ragas) (6.0.3)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from openai>=1.0.0->ragas) (4.12.1)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from openai>=1.0.0->ragas) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from openai>=1.0.0->ragas) (0.28.1)
Requirement already satisfied: jiter<1,>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from openai>=1.0.0->ragas) (0.13.0)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from openai>=1.0.0->ragas) (1.3.1)
Requirement already satisfied: typing-extensions<5,>=4.11 in /usr/local/lib/python3.12/dist-packages (from openai>=1.0.0->ragas) (4.15.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0.0->ragas) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0.0->ragas) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0.0->ragas) (0.4.2)
Requirement already satisfied: aiohttp<4.0.0,>=3.9.1 in /usr/local/lib/python3.12/dist-packages (from instructor->ragas) (3.13.3)
Requirement already satisfied: docstring-parser<1.0,>=0.16 in /usr/local/lib/python3.12/dist-packages (from instructor->ragas) (0.17.0)
Requirement already satisfied: jinja2<4.0.0,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from instructor->ragas) (3.1.6)
Collecting jiter<1,>=0.10.0 (from openai>=1.0.0->ragas)
  Downloading jiter-0.11.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.2 kB)
Requirement already satisfied: tenacity<10.0.0,>=8.2.3 in /usr/local/lib/python3.12/dist-packages (from instructor->ragas) (9.1.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->ragas) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->ragas) (2.19.2)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->ragas) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->ragas) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->ragas) (0.0.4)
Requirement already satisfied: langgraph<1.1.0,>=1.0.8 in /usr/local/lib/python3.12/dist-packages (from langchain->ragas) (1.0.9)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core->ragas) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /usr/local/lib/python3.12/dist-packages (from langchain-core->ragas) (0.7.7)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core->ragas) (0.14.1)
Collecting langchain-classic<2.0.0,>=1.0.0 (from langchain-community->ragas)
  Downloading langchain_classic-1.0.2-py3-none-any.whl.metadata (4.8 kB)
Requirement already satisfied: SQLAlchemy<3.0.0,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community->ragas) (2.0.47)
Collecting requests>=2.32.2 (from datasets>=4.0.0->ragas)
  Downloading requests-2.32.5-py3-none-any.whl.metadata (4.9 kB)
Collecting dataclasses-json<0.7.0,>=0.6.7 (from langchain-community->ragas)
  Downloading dataclasses_json-0.6.7-py3-none-any.whl.metadata (25 kB)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in /usr/local/lib/python3.12/dist-packages (from langchain-community->ragas) (2.13.1)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community->ragas) (0.4.3)
Requirement already satisfied: regex>=2022.1.18 in /usr/local/lib/python3.12/dist-packages (from tiktoken->ragas) (2025.11.3)
Requirement already satisfied: scipy>=1.7.3 in /usr/local/lib/python3.12/dist-packages (from scikit-network->ragas) (1.16.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.9.1->instructor->ragas) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.9.1->instructor->ragas) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.9.1->instructor->ragas) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.9.1->instructor->ragas) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.9.1->instructor->ragas) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.9.1->instructor->ragas) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.9.1->instructor->ragas) (1.22.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=3.5.0->openai>=1.0.0->ragas) (3.11)
Collecting marshmallow<4.0.0,>=3.18.0 (from dataclasses-json<0.7.0,>=0.6.7->langchain-community->ragas)
  Downloading marshmallow-3.26.2-py3-none-any.whl.metadata (7.3 kB)
Collecting typing-inspect<1,>=0.4.0 (from dataclasses-json<0.7.0,>=0.6.7->langchain-community->ragas)
  Downloading typing_inspect-0.9.0-py3-none-any.whl.metadata (1.5 kB)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai>=1.0.0->ragas) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai>=1.0.0->ragas) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai>=1.0.0->ragas) (0.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets>=4.0.0->ragas) (1.3.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2<4.0.0,>=3.1.4->instructor->ragas) (3.0.3)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core->ragas) (3.0.0)
Collecting langchain-core (from ragas)
  Downloading langchain_core-1.2.17-py3-none-any.whl.metadata (4.4 kB)
Collecting langchain-text-splitters<2.0.0,>=1.1.0 (from langchain-classic<2.0.0,>=1.0.0->langchain-community->ragas)
  Downloading langchain_text_splitters-1.1.1-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: langgraph-checkpoint<5.0.0,>=2.1.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.1.0,>=1.0.8->langchain->ragas) (4.0.0)
Requirement already satisfied: langgraph-prebuilt<1.1.0,>=1.0.8 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.1.0,>=1.0.8->langchain->ragas) (1.0.8)
Requirement already satisfied: langgraph-sdk<0.4.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.1.0,>=1.0.8->langchain->ragas) (0.3.9)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core->ragas) (3.11.7)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core->ragas) (1.0.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core->ragas) (0.25.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->ragas) (0.1.2)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community->ragas) (1.2.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=4.0.0->ragas) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=4.0.0->ragas) (2.5.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from SQLAlchemy<3.0.0,>=1.4.0->langchain-community->ragas) (3.3.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=4.0.0->ragas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=4.0.0->ragas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=4.0.0->ragas) (2025.3)
Requirement already satisfied: ormsgpack>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from langgraph-checkpoint<5.0.0,>=2.1.0->langgraph<1.1.0,>=1.0.8->langchain->ragas) (1.12.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets>=4.0.0->ragas) (1.17.0)
Collecting mypy-extensions>=0.3.0 (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7.0,>=0.6.7->langchain-community->ragas)
  Downloading mypy_extensions-1.1.0-py3-none-any.whl.metadata (1.1 kB)
Downloading ragas-0.4.3-py3-none-any.whl (466 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 466.5/466.5 kB 35.4 MB/s eta 0:00:00
Downloading diskcache-5.6.3-py3-none-any.whl (45 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.5/45.5 kB 5.7 MB/s eta 0:00:00
Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Downloading instructor-1.14.5-py3-none-any.whl (177 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 177.4/177.4 kB 21.3 MB/s eta 0:00:00
Downloading langchain_community-0.4.1-py3-none-any.whl (2.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 98.9 MB/s eta 0:00:00
Downloading langchain_openai-1.1.10-py3-none-any.whl (87 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.2/87.2 kB 11.3 MB/s eta 0:00:00
Downloading scikit_network-0.33.5-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (8.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.0/8.0 MB 99.5 MB/s eta 0:00:00
Downloading dataclasses_json-0.6.7-py3-none-any.whl (28 kB)
Downloading jiter-0.11.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (358 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 358.8/358.8 kB 38.2 MB/s eta 0:00:00
Downloading langchain_classic-1.0.2-py3-none-any.whl (1.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 67.0 MB/s eta 0:00:00
Downloading langchain_core-1.2.17-py3-none-any.whl (502 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 502.7/502.7 kB 46.2 MB/s eta 0:00:00
Downloading requests-2.32.5-py3-none-any.whl (64 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.7/64.7 kB 8.2 MB/s eta 0:00:00
Downloading langchain_text_splitters-1.1.1-py3-none-any.whl (35 kB)
Downloading marshmallow-3.26.2-py3-none-any.whl (50 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.0/51.0 kB 6.5 MB/s eta 0:00:00
Downloading typing_inspect-0.9.0-py3-none-any.whl (8.8 kB)
Downloading mypy_extensions-1.1.0-py3-none-any.whl (5.0 kB)
Installing collected packages: appdirs, requests, mypy-extensions, marshmallow, jiter, diskcache, typing-inspect, scikit-network, dataclasses-json, langchain-core, instructor, langchain-text-splitters, langchain_openai, langchain-classic, langchain-community, ragas
  Attempting uninstall: requests
    Found existing installation: requests 2.32.4
    Uninstalling requests-2.32.4:
      Successfully uninstalled requests-2.32.4
  Attempting uninstall: jiter
    Found existing installation: jiter 0.13.0
    Uninstalling jiter-0.13.0:
      Successfully uninstalled jiter-0.13.0
  Attempting uninstall: langchain-core
    Found existing installation: langchain-core 1.2.16
    Uninstalling langchain-core-1.2.16:
      Successfully uninstalled langchain-core-1.2.16
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires requests==2.32.4, but you have requests 2.32.5 which is incompatible.
Successfully installed appdirs-1.4.4 dataclasses-json-0.6.7 diskcache-5.6.3 instructor-1.14.5 jiter-0.11.1 langchain-classic-1.0.2 langchain-community-0.4.1 langchain-core-1.2.17 langchain-text-splitters-1.1.1 langchain_openai-1.1.10 marshmallow-3.26.2 mypy-extensions-1.1.0 ragas-0.4.3 requests-2.32.5 scikit-network-0.33.5 typing-inspect-0.9.0

In [ ]:
import torch

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device

device(type='cuda')

In [ ]:
import pandas as pd
import json
from tqdm import tqdm
from ragas import EvaluationDataset

df = pd.read_csv("Eval_results_full_set_50.csv")

dataset_list = []

for _, row in tqdm(df.iterrows(), total=len(df)):

    # retrieved contexts
    contexts = []

    try:
        ids = json.loads(row["retrieved_chunk_ids"])
        contexts = ids  # replace with real text if available
    except:
        contexts = []

    dataset_list.append({
        "user_input": row["question"],
        "reference": row["ground_truth"],
        "response": row["answer"],
        "retrieved_contexts": contexts
    })

dataset = EvaluationDataset.from_list(dataset_list)

print(dataset.features())

/usr/local/lib/python3.12/dist-packages/google/colab/_import_hooks/_hook_injector.py:55: FutureWarning:

All support for the `google.generativeai` package has ended. It will no longer be receiving
updates or bug fixes. Please switch to the `google.genai` package as soon as possible.
See README for more details:

https://github.com/google-gemini/deprecated-generative-ai-python/blob/main/README.md

  loader.exec_module(module)
100%|██████████| 50/50 [00:00<00:00, 6270.26it/s]

['user_input', 'retrieved_contexts', 'response', 'reference']

In [ ]:
from langchain_community.chat_models import ChatOllama
from ragas.llms import LangchainLLMWrapper

llm = ChatOllama(
    model="llama3.2",
    temperature=0.1
)

llm_wrapper = LangchainLLMWrapper(llm)

/tmp/ipykernel_4234/2598989954.py:4: LangChainDeprecationWarning: The class `ChatOllama` was deprecated in LangChain 0.3.1 and will be removed in 1.0.0. An updated version of the class exists in the `langchain-ollama package and should be used instead. To use it run `pip install -U `langchain-ollama` and import as `from `langchain_ollama import ChatOllama``.
  llm = ChatOllama(
/tmp/ipykernel_4234/2598989954.py:9: DeprecationWarning: LangchainLLMWrapper is deprecated and will be removed in a future version. Use llm_factory instead: from openai import OpenAI; from ragas.llms import llm_factory; llm = llm_factory('gpt-4o-mini', client=OpenAI(api_key='...'))
  llm_wrapper = LangchainLLMWrapper(llm)

In [ ]:
from ragas.metrics import (
    BleuScore,
    ContextRecall,
    Faithfulness,
    FactualCorrectness
)

/tmp/ipykernel_4234/447493662.py:1: DeprecationWarning: Importing BleuScore from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import BleuScore
  from ragas.metrics import (
/tmp/ipykernel_4234/447493662.py:1: DeprecationWarning: Importing ContextRecall from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import ContextRecall
  from ragas.metrics import (
/tmp/ipykernel_4234/447493662.py:1: DeprecationWarning: Importing Faithfulness from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import Faithfulness
  from ragas.metrics import (
/tmp/ipykernel_4234/447493662.py:1: DeprecationWarning: Importing FactualCorrectness from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import FactualCorrectness
  from ragas.metrics import (

In [ ]:
!pip install sacrebleu

Collecting sacrebleu
  Downloading sacrebleu-2.6.0-py3-none-any.whl.metadata (39 kB)
Collecting portalocker (from sacrebleu)
  Downloading portalocker-3.2.0-py3-none-any.whl.metadata (8.7 kB)
Requirement already satisfied: regex in /usr/local/lib/python3.12/dist-packages (from sacrebleu) (2025.11.3)
Requirement already satisfied: tabulate>=0.8.9 in /usr/local/lib/python3.12/dist-packages (from sacrebleu) (0.9.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from sacrebleu) (2.0.2)
Collecting colorama (from sacrebleu)
  Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (from sacrebleu) (6.0.2)
Downloading sacrebleu-2.6.0-py3-none-any.whl (100 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.8/100.8 kB 9.8 MB/s eta 0:00:00
Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Downloading portalocker-3.2.0-py3-none-any.whl (22 kB)
Installing collected packages: portalocker, colorama, sacrebleu
Successfully installed colorama-0.4.6 portalocker-3.2.0 sacrebleu-2.6.0

In [ ]:
from ragas import evaluate
import time

metrics = [
    BleuScore(),
    ContextRecall(),
    Faithfulness(),
    FactualCorrectness(mode="f1")
]

print("Starting RAGAS evaluation...")

start = time.time()

results = evaluate(
    dataset=dataset,
    metrics=metrics,
    llm=llm_wrapper,
    show_progress=True
)

end = time.time()

print("\nEvaluation finished in", round(end-start,2), "seconds")
print(results)

Starting RAGAS evaluation...

Evaluating:   0%|          | 0/200 [00:00<?, ?it/s]

ERROR:ragas.executor:Exception raised in Job[1]: ClientConnectorError(Cannot connect to host localhost:11434 ssl:default [Connect call failed ('127.0.0.1', 11434)])
ERROR:ragas.executor:Exception raised in Job[7]: ClientConnectorError(Cannot connect to host localhost:11434 ssl:default [Connect call failed ('127.0.0.1', 11434)])
ERROR:ragas.executor:Exception raised in Job[3]: ClientConnectorError(Cannot connect to host localhost:11434 ssl:default [Connect call failed ('127.0.0.1', 11434)])
ERROR:ragas.executor:Exception raised in Job[15]: ClientConnectorError(Cannot connect to host localhost:11434 ssl:default [Connect call failed ('127.0.0.1', 11434)])
ERROR:ragas.executor:Exception raised in Job[19]: ClientConnectorError(Cannot connect to host localhost:11434 ssl:default [Connect call failed ('127.0.0.1', 11434)])
ERROR:ragas.executor:Exception raised in Job[17]: ClientConnectorError(Cannot connect to host localhost:11434 ssl:default [Connect call failed ('127.0.0.1', 11434)])
ERROR:ragas.executor:Exception raised in Job[21]: ClientConnectorError(Cannot connect to host localhost:11434 ssl:default [Connect call failed ('127.0.0.1', 11434)])
ERROR:ragas.executor:Exception raised in Job[2]: ClientConnectorError(Cannot connect to host localhost:11434 ssl:default [Connect call failed ('127.0.0.1', 11434)])
ERROR:ragas.executor:Exception raised in Job[11]: ClientConnectorError(Cannot connect to host localhost:11434 ssl:default [Connect call failed ('127.0.0.1', 11434)])
ERROR:ragas.executor:Exception raised in Job[18]: ClientConnectorError(Cannot connect to host localhost:11434 ssl:default [Connect call failed ('127.0.0.1', 11434)])
ERROR:ragas.executor:Exception raised in Job[29]: ClientConnectorError(Cannot connect to host localhost:11434 ssl:default [Connect call failed ('127.0.0.1', 11434)])
ERROR:ragas.executor:Exception raised in Job[5]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[6]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[9]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[10]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[13]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[14]: TimeoutError()
WARNING:ragas.metrics._faithfulness:No statements were generated from the answer.
ERROR:ragas.executor:Exception raised in Job[23]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[26]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[27]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[30]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[31]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[35]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[38]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[39]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[41]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[42]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[43]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[45]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[46]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[47]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[50]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[51]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[54]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[55]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[59]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[67]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[70]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[71]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[74]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[75]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[78]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[79]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[83]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[86]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[87]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[91]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[95]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[98]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[99]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[102]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[103]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[106]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[107]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[110]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[111]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[114]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[115]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[118]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[122]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[126]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[127]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[130]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[131]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[134]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[135]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[138]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[146]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[154]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[155]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[159]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[162]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[163]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[166]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[167]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[170]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[175]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[178]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[182]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[183]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[186]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[187]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[190]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[191]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[194]: TimeoutError()

Evaluation finished in 1431.63 seconds
{'bleu_score': 0.1217, 'context_recall': 0.7976, 'faithfulness': 0.7937, 'factual_correctness(mode=f1)': 0.5109}

In [ ]:
from ragas.metrics import (
    BleuScore,
    ContextRecall,
    ContextPrecision,
    Faithfulness,
    FactualCorrectness,
    AnswerRelevancy,
    ContextUtilization,
    NoiseSensitivity
)

metrics = [
    BleuScore(),
    ContextRecall(),
    ContextPrecision(),
    Faithfulness(),
    FactualCorrectness(mode="f1"),
    AnswerRelevancy(),
    ContextUtilization(),
    NoiseSensitivity()
]

/tmp/ipykernel_4234/2461196835.py:1: DeprecationWarning: Importing BleuScore from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import BleuScore
  from ragas.metrics import (
/tmp/ipykernel_4234/2461196835.py:1: DeprecationWarning: Importing ContextRecall from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import ContextRecall
  from ragas.metrics import (
/tmp/ipykernel_4234/2461196835.py:1: DeprecationWarning: Importing ContextPrecision from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import ContextPrecision
  from ragas.metrics import (
/tmp/ipykernel_4234/2461196835.py:1: DeprecationWarning: Importing Faithfulness from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import Faithfulness
  from ragas.metrics import (
/tmp/ipykernel_4234/2461196835.py:1: DeprecationWarning: Importing FactualCorrectness from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import FactualCorrectness
  from ragas.metrics import (
/tmp/ipykernel_4234/2461196835.py:1: DeprecationWarning: Importing AnswerRelevancy from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import AnswerRelevancy
  from ragas.metrics import (
/tmp/ipykernel_4234/2461196835.py:1: DeprecationWarning: Importing ContextUtilization from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import ContextUtilization
  from ragas.metrics import (
/tmp/ipykernel_4234/2461196835.py:1: DeprecationWarning: Importing NoiseSensitivity from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import NoiseSensitivity
  from ragas.metrics import (

In [ ]:
scores = evaluate(
    dataset=dataset,
    metrics=metrics,
    llm=llm_wrapper,
    show_progress=True
)

In [ ]:
import pandas as pd
import json
from tqdm import tqdm
from ragas import EvaluationDataset

df = pd.read_csv("Eval_results_full_set_50.csv")

dataset_list = []

for _, row in tqdm(df.iterrows(), total=len(df)):

    # retrieved contexts
    contexts = []

    try:
        ids = json.loads(row["retrieved_chunk_ids"])
        contexts = ids  # replace with real text if available
    except:
        contexts = []

    dataset_list.append({
        "user_input": row["question"],
        "reference": row["ground_truth"],
        "response": row["answer"],
        "retrieved_contexts": contexts
    })

dataset = EvaluationDataset.from_list(dataset_list)

print(dataset.features())

100%|██████████| 50/50 [00:00<00:00, 4666.04it/s]

['user_input', 'retrieved_contexts', 'response', 'reference']

In [ ]:
from langchain_community.chat_models import ChatOllama
from ragas.llms import LangchainLLMWrapper

# llm = ChatOllama(
#     model="llama3.2",
#     temperature=0.1
# )
llm = ChatOllama(
    model="llama3.2",
    temperature=0
)

llm_wrapper = LangchainLLMWrapper(llm)

/tmp/ipykernel_4234/3037046647.py:13: DeprecationWarning: LangchainLLMWrapper is deprecated and will be removed in a future version. Use llm_factory instead: from openai import OpenAI; from ragas.llms import llm_factory; llm = llm_factory('gpt-4o-mini', client=OpenAI(api_key='...'))
  llm_wrapper = LangchainLLMWrapper(llm)

In [ ]:
# # from ragas import evaluate
# # from ragas.metrics import (
# #     BleuScore,
# #     ContextRecall,
# #     ContextPrecision,
# #     Faithfulness,
# #     FactualCorrectness,
# #     AnswerRelevancy
# # )

# # from tqdm import tqdm
# # import time
# # import pandas as pd

# # print("Starting RAGAS evaluation...")

# # # Define metrics
# # # metrics = [
# # #     BleuScore(),
# # #     ContextRecall(),
# # #     ContextPrecision(),
# # #     Faithfulness(),
# # #     FactualCorrectness(mode="f1"),
# # #     AnswerRelevancy()
# # # ]

# # metrics = [
# #     BleuScore(),
# #     ContextRecall(),
# #     ContextPrecision(),
# #     Faithfulness(),
# #     FactualCorrectness(mode="f1"),
# #     AnswerRelevancy(),
# #     ContextUtilization(),
# #     NoiseSensitivity()
# # ]

# # # Start timer
# # start = time.time()

# # # Run evaluation
# # results = evaluate(
# #     dataset=dataset,
# #     metrics=metrics,
# #     llm=llm_wrapper,
# #     show_progress=True
# # )

# # # End timer
# # end = time.time()

# # print("\nEvaluation finished in", round(end-start,2), "seconds\n")

# # # Convert results to dictionary
# # scores = results.to_dict()

# # # Pretty print results
# # print("===== RAGAS METRICS =====")

# # for metric, score in scores.items():
# #     print(f"{metric}: {round(score,4)}")
# from ragas import evaluate
# from ragas.metrics.collections import (
#     BleuScore,
#     ContextRecall,
#     ContextPrecision,
#     Faithfulness,
#     FactualCorrectness,
#     AnswerRelevancy
# )

# import time

# print("Starting RAGAS evaluation...")

# metrics = [
#     BleuScore(),
#     ContextRecall(llm=llm_wrapper),
#     ContextPrecision(llm=llm_wrapper),
#     Faithfulness(llm=llm_wrapper),
#     FactualCorrectness(llm=llm_wrapper, mode="f1"),
#     AnswerRelevancy(llm=llm_wrapper),
#     ContextUtilization(llm=llm_wrapper),
#     NoiseSensitivity(llm=llm_wrapper)

# ]


# start = time.time()

# results = evaluate(
#     dataset=dataset,
#     metrics=metrics,
#     llm=llm_wrapper,
#     show_progress=True
# )

# end = time.time()

# print("\nEvaluation finished in", round(end-start,2), "seconds")

# scores = results.to_dict()

# print("\n===== RAGAS METRICS =====")

# for metric, score in scores.items():
#     print(f"{metric}: {round(score,4)}")

Starting RAGAS evaluation...

ValueError: Collections metrics only support modern InstructorLLM. Found: LangchainLLMWrapper. Use: llm_factory('gpt-4o-mini', client=openai_client)

In [ ]:
pd.DataFrame([scores]).to_csv("ragas_scores.csv", index=False)

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv("/content/processing_history_20260223_100815.csv")
df.head()

,ID,Filename,Output File,Status,Method,Created,Duration (s),Size (KB),Gender,Language,Surrogate,Error
0,1264,call_20230504_018.wav,anonymized_20260220_094641_327.wav,completed,both,2026-02-20 09:46:09,31.57,20886.6,female,english,english_female_person_PERSON,NaN
1,1263,call_20230504_018.wav,anonymized_20260220_094010_322.wav,completed,both,2026-02-20 09:39:29,41.25,20886.6,female,english,english_female_person_PERSON,NaN
2,1262,call_20230523_001.wav,anonymized_20260220_091932_164.wav,completed,both,2026-02-20 09:19:22,11.89,10106.3,female,english,english_female_person_PERSON,NaN
3,1261,call_20230523_001.wav,anonymized_20260220_091913_685.wav,completed,both,2026-02-20 09:18:49,25.09,10106.3,female,english,english_female_person_PERSON,NaN
4,1260,call_20230523_001.wav,anonymized_20260220_091713_895.wav,completed,both,2026-02-20 09:16:53,20.80,10106.3,female,english,english_female_person_PERSON,NaN

In [ ]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
ID,1000.0,764.500000,288.819436,265.00,514.75,764.50,1014.250,1264.00
Duration (s),995.0,6.237829,5.625332,0.04,2.85,4.72,7.895,57.34
Size (KB),1000.0,4309.651400,2885.183376,495.10,2403.20,3396.30,5286.300,20886.60
Error,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df['Filename'].is_unique

False

In [ ]:
duplicate_filenames = df[df['Filename'].duplicated(keep=False)]
display(duplicate_filenames.sort_values(by='Filename'))

,ID,Filename,Output File,Status,Method,Created,Duration (s),Size (KB),Gender,Language,Surrogate,Error
913,351,WhatsApp Audio 2026-01-13 at 11.39.55 AM.mp3,anonymized_20260208_122711_227.wav,completed,both,2026-02-08 12:27:10,0.69,495.1,male,english,english_male_person_PERSON,NaN
741,523,WhatsApp Audio 2026-01-13 at 11.39.55 AM.mp3,anonymized_20260211_062611_931.wav,completed,both,2026-02-11 06:26:08,3.57,495.1,male,english,english_male_person_PERSON,NaN
892,372,WhatsApp Audio 2026-01-13 at 11.39.55 AM.mp3,NaN,processing,both,2026-02-09 11:26:42,NaN,495.1,male,english,NaN,NaN
912,352,WhatsApp Audio 2026-01-13 at 11.39.55 AM.mp3,anonymized_20260208_123343_997.wav,completed,both,2026-02-08 12:33:19,25.04,495.1,male,english,english_male_person_PERSON,NaN
939,325,WhatsApp Audio 2026-01-13 at 11.39.55 AM.mp3,NaN,processing,both,2026-02-01 13:01:19,NaN,495.1,male,english,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
217,1047,call_20250424_003.wav,anonymized_20260213_121003_114.wav,completed,both,2026-02-13 12:09:55,7.93,6481.9,female,english,english_female_person_PERSON,NaN
203,1061,call_20250429_006.wav,anonymized_20260213_123737_695.wav,completed,both,2026-02-13 12:37:02,35.73,13346.3,male,english,english_male_person_PERSON,NaN
205,1059,call_20250429_006.wav,anonymized_20260213_123449_633.wav,completed,both,2026-02-13 12:34:33,16.09,13346.3,male,english,english_male_person_PERSON,NaN
206,1058,call_20250429_006.wav,anonymized_20260213_123329_442.wav,completed,both,2026-02-13 12:33:11,17.85,13346.3,male,english,english_male_person_PERSON,NaN
204,1060,call_20250429_006.wav,anonymized_20260213_123621_796.wav,completed,both,2026-02-13 12:35:54,27.54,13346.3,male,english,english_male_person_PERSON,NaN

In [ ]:
duplicate_filenames.shape

(920, 12)

In [ ]:
duplicate_filenames.sort_values(by='Filename').head()

,ID,Filename,Output File,Status,Method,Created,Duration (s),Size (KB),Gender,Language,Surrogate,Error
913,351,WhatsApp Audio 2026-01-13 at 11.39.55 AM.mp3,anonymized_20260208_122711_227.wav,completed,both,2026-02-08 12:27:10,0.69,495.1,male,english,english_male_person_PERSON,NaN
741,523,WhatsApp Audio 2026-01-13 at 11.39.55 AM.mp3,anonymized_20260211_062611_931.wav,completed,both,2026-02-11 06:26:08,3.57,495.1,male,english,english_male_person_PERSON,NaN
892,372,WhatsApp Audio 2026-01-13 at 11.39.55 AM.mp3,NaN,processing,both,2026-02-09 11:26:42,NaN,495.1,male,english,NaN,NaN
912,352,WhatsApp Audio 2026-01-13 at 11.39.55 AM.mp3,anonymized_20260208_123343_997.wav,completed,both,2026-02-08 12:33:19,25.04,495.1,male,english,english_male_person_PERSON,NaN
939,325,WhatsApp Audio 2026-01-13 at 11.39.55 AM.mp3,NaN,processing,both,2026-02-01 13:01:19,NaN,495.1,male,english,NaN,NaN

In [ ]:
duplicate_filenames.tail()

,ID,Filename,Output File,Status,Method,Created,Duration (s),Size (KB),Gender,Language,Surrogate,Error
994,270,call_20240104_001.wav,anonymized_20260129_094611_572.wav,completed,both,2026-01-29 09:46:06,5.51,4567.9,female,english,english_female_person_PERSON,NaN
995,269,call_20240104_001.wav,anonymized_20260129_094402_683.wav,completed,both,2026-01-29 09:43:56,6.39,4567.9,female,english,english_female_person_PERSON,NaN
997,267,call_20240101_007.wav,anonymized_20260129_090614_355.wav,completed,both,2026-01-29 09:06:12,2.29,2245.0,female,english,english_female_person_PERSON,NaN
998,266,call_20240101_007.wav,anonymized_20260129_090546_071.wav,completed,both,2026-01-29 09:05:43,2.67,2245.0,female,english,english_female_person_PERSON,NaN
999,265,call_20240101_007.wav,anonymized_20260129_090506_509.wav,completed,both,2026-01-29 09:05:00,5.99,2245.0,female,english,english_female_person_PERSON,NaN

In [ ]:
duplicate_filenames.to_csv('duplicate_filenames.csv', index=False)

In [ ]:
duplicate_filenames

In [ ]:
duplicate_filenames.head()

,ID,Filename,Output File,Status,Method,Created,Duration (s),Size (KB),Gender,Language,Surrogate,Error
0,1264,call_20230504_018.wav,anonymized_20260220_094641_327.wav,completed,both,2026-02-20 09:46:09,31.57,20886.6,female,english,english_female_person_PERSON,NaN
1,1263,call_20230504_018.wav,anonymized_20260220_094010_322.wav,completed,both,2026-02-20 09:39:29,41.25,20886.6,female,english,english_female_person_PERSON,NaN
2,1262,call_20230523_001.wav,anonymized_20260220_091932_164.wav,completed,both,2026-02-20 09:19:22,11.89,10106.3,female,english,english_female_person_PERSON,NaN
3,1261,call_20230523_001.wav,anonymized_20260220_091913_685.wav,completed,both,2026-02-20 09:18:49,25.09,10106.3,female,english,english_female_person_PERSON,NaN
4,1260,call_20230523_001.wav,anonymized_20260220_091713_895.wav,completed,both,2026-02-20 09:16:53,20.80,10106.3,female,english,english_female_person_PERSON,NaN

In [ ]:
duplicate_filenames = df[df['Filename'].duplicated(keep=False)]
display(duplicate_filenames.sort_values(by='Filename'))

In [ ]:
repetitions_count = duplicate_filenames['Filename'].value_counts().reset_index()
repetitions_count.columns = ['Filename', 'Repetitions']
display(repetitions_count.head())

                Filename  Repetitions
0  call_20240617_001.wav           22
1  call_20241115_001.wav           17
2  call_20241212_005.wav           17
3  call_20240920_001.wav           13
4  call_20240930_001.wav           10

In [ ]:
print(f"Total unique filenames with repetitions: {repetitions_count.shape[0]}")

Total unique filenames with repetitions: 222